# -*- coding: utf-8 -*-
from common import Q

D = 0  # D1 — Agent Architecture & Orchestration

# ---------------------------------------------------------------- standard ---

Q("d1s01", D, "standard", "Customer support agent",
  "You are writing the agent loop for a support agent on the Messages API. After every call you must decide whether to run the requested tools and call Claude again, or stop and present the answer to the customer. What determines that decision?",
  "Read response.stop_reason: \"tool_use\" means run the tools and call again, \"end_turn\" means the turn is finished.",
  ["Check whether the response contains assistant text — if Claude produced an explanation, the work is finished.",
   "Search the response text for closing phrases such as \"I'm done\" or \"anything else?\", which signal completion.",
   "Set a maximum iteration count of around ten calls and stop there, whatever Claude indicates."],
  "stop_reason is the explicit structured control signal. Text parsing is guesswork, a response can contain both text and a tool_use block, and an iteration cap is a safety net that either truncates real work or burns turns."),

Q("d1s02", D, "standard", "Agentic AI tools",
  "Claude has returned a tool_use block, your code has executed the tool, and you now have the result. How is that result added to the conversation before the next request?",
  "As a user-role message whose content is a tool_result block carrying the matching tool_use_id.",
  ["As an assistant-role message containing a tool_result block, since the tool acted on Claude's behalf.",
   "As a message with the dedicated \"tool\" role, which the API reserves for tool output.",
   "As an extra field on the original assistant message, so the request and its result stay together."],
  "The Messages API has only user and assistant roles. Tool output comes back as a user-role message containing tool_result blocks, each referencing the tool_use_id it answers."),

Q("d1s03", D, "standard", "Conversational AI architecture",
  "Users refine their playlist preferences over several turns. Two messages after a user said \"I love jazz\", Claude asks \"What genres do you enjoy?\". What is the most likely cause?",
  "Your application is not including the earlier messages in the messages array of each request.",
  ["The conversation has exceeded the model's context window and the earliest turns were dropped.",
   "The Messages API needs a session_id parameter to associate requests with the same conversation.",
   "Server-side memory requires a vector store to be attached before earlier turns can be recalled."],
  "The API is stateless: every request must carry the history you want Claude to see. Two messages cannot overflow a context window, and neither session identifiers nor vector stores are part of how the API keeps state."),

Q("d1s04", D, "standard", "Multi-agent research system",
  "A colleague proposes that the document analysis agent send its results straight to the synthesis agent instead of going back through the coordinator. What is the main argument for keeping the coordinator as the central hub?",
  "The coordinator sees every interaction, so errors are handled uniformly and it controls what each subagent receives.",
  ["Only the coordinator can serialise messages between agents, because subagents use isolated memory spaces.",
   "Routing through the coordinator is what makes automatic retries possible; direct calls cannot be retried.",
   "The coordinator batches subagent requests together, which cuts the number of API calls and total latency."],
  "Hub-and-spoke exists for observability and control: one place sees every exchange, applies the same error handling, and decides what information each subagent is given. Retries and serialisation are not what the topology buys you."),

Q("d1s05", D, "standard", "Multi-agent research system",
  "The web-search and document-analysis agents have both finished and returned their results to the coordinator. What happens next in a coordinator–subagent research system?",
  "The coordinator hands both result sets to the synthesis agent for a single integrated pass.",
  ["The coordinator concatenates the two raw outputs and returns them as the finished report.",
   "Each agent forwards its own results to the report-writing agent so synthesis can start sooner.",
   "The document analysis agent pulls in the web-search results and merges them internally before reporting."],
  "Integration is the synthesis agent's job, and the coordinator is what feeds it. Concatenation is not synthesis, and any path that skips the coordinator gives up the control the pattern exists to provide."),

Q("d1s06", D, "standard", "Multi-agent research system",
  "A coordinator spawns a document analysis subagent with the Task tool. The subagent keeps producing shallow output that ignores what earlier agents already found. What does the coordinator have to change?",
  "Put everything the subagent needs into the Task prompt itself — the document, prior findings and the expected output shape.",
  ["Give the subagent a longer system prompt so it knows to consult the coordinator's earlier conversation.",
   "Raise the subagent's max_tokens so it has room to reason over the coordinator's accumulated history.",
   "Have the subagent call back to the coordinator for context whenever its own prompt is insufficient."],
  "Subagents start with an empty context and inherit none of the coordinator's history. Anything they need has to be passed explicitly in the prompt; no setting makes context leak across the boundary."),

Q("d1s07", D, "standard", "Multi-agent research system",
  "Your coordinator agent is defined with allowed_tools set to [\"get_customer\", \"lookup_order\"], and it never delegates anything. Subagent definitions look correct. What is wrong?",
  "\"Task\" is missing from the coordinator's allowed tools, so it has no way to spawn a subagent.",
  ["Subagent definitions have to be listed in the coordinator's allowed_tools by name before they can be invoked.",
   "A coordinator can only delegate when its system prompt names each subagent and the order to call them in.",
   "Delegation requires the subagents to be started first; a coordinator cannot create them on demand."],
  "Spawning a subagent is a tool call like any other. Without \"Task\" in its allowed tools the coordinator simply cannot delegate, however well the subagents are defined."),

Q("d1s08", D, "standard", "Multi-agent research system",
  "A coordinator needs four independent literature searches. Each takes about 40 seconds, and the run currently takes almost three minutes. How do you cut wall-clock time without changing what is researched?",
  "Issue the four Task calls in a single coordinator turn so the subagents run in parallel.",
  ["Merge the four searches into one subagent prompt so a single agent covers all four areas in one pass.",
   "Give the coordinator a larger model so it works through the four delegations faster.",
   "Cache each subagent's result so repeated runs of the same search return immediately."],
  "Several Task calls emitted in one coordinator turn run concurrently. Merging them back into one agent removes the parallelism, a bigger model does not make sequential delegation concurrent, and caching only helps on a repeat run."),

Q("d1s09", D, "standard", "Customer support agent",
  "Logs show that in 12% of conversations the agent skips get_customer and calls lookup_order with only the name the customer typed, which has produced refunds on the wrong account. What fixes this most effectively?",
  "A programmatic precondition that blocks lookup_order and process_refund until get_customer has returned a verified customer id.",
  ["A strengthened system prompt stating that verification through get_customer is mandatory before any order operation.",
   "Few-shot examples showing the agent calling get_customer first even when the customer volunteers order details.",
   "A routing classifier that inspects each request and exposes only the subset of tools appropriate to it."],
  "Where a tool sequence carries financial consequences, only code gives a deterministic guarantee. Prompt wording and examples raise compliance without ever reaching certainty, and a classifier controls availability rather than ordering."),

Q("d1s10", D, "standard", "Customer support agent",
  "Your agent misreads tool output: get_customer returns Unix timestamps, lookup_order returns ISO 8601 dates, and a third-party MCP server you cannot modify returns numeric status codes. What is the most maintainable way to normalise this?",
  "A PostToolUse hook that rewrites tool output into consistent formats before the agent ever sees it.",
  ["A normalize_data tool that the agent is instructed to call after every retrieval to convert the values.",
   "Detailed documentation of each tool's conventions in the system prompt so the agent converts as it reads.",
   "Wrappers around the tools you own plus format fixes inside them, leaving third-party output as it is."],
  "A PostToolUse hook is one deterministic place that covers every tool, third-party servers included. The alternatives either depend on the model remembering to convert, or leave the servers you do not control untouched."),

Q("d1s11", D, "standard", "Customer support agent",
  "Company policy says refunds above $500 always need a human. The agent occasionally processes a $700 refund anyway. Which control actually enforces the rule?",
  "A pre-call hook that inspects process_refund arguments and redirects anything above the threshold to escalation.",
  ["A policy section in the system prompt stating the $500 limit and requiring escalation above it.",
   "Few-shot examples in the prompt showing large refunds being escalated rather than processed.",
   "A post-hoc audit job that flags refunds above $500 so they can be reversed the following day."],
  "Financial limits are business rules, and business rules belong in code. Prompt instructions and examples are probabilistic; an audit that reverses the payment afterwards is not prevention."),

Q("d1s12", D, "standard", "Structured data extraction",
  "An invoice pipeline runs the same five steps on every document: parse, extract metadata, extract line items, validate, enrich. Output must be reproducible across runs. Which decomposition strategy fits?",
  "A fixed pipeline, where each step is defined up front and always runs in the same order.",
  ["Dynamic decomposition, so the agent can generate the steps each document actually needs.",
   "A single prompt containing all five instructions, letting the model order the work itself.",
   "A coordinator that picks a subset of the five steps per document based on its first impression."],
  "When the steps are known in advance and reproducibility is the point, a fixed chain is the right shape. Adaptive decomposition earns its unpredictability only when the work genuinely varies."),

Q("d1s13", D, "standard", "Customer support agent",
  "The agent has decided to escalate a billing dispute to a human operator. What does the handoff have to contain?",
  "A self-contained summary: customer id, issue, order id, root cause, what has already been done and what is recommended.",
  ["A link to the live conversation so the operator can read the transcript and form their own view.",
   "The customer's last message plus the agent's confidence score, keeping the handoff short to read.",
   "The full message history verbatim, so nothing the agent observed is lost in summarisation."],
  "The operator works from the handoff object, not from your transcript. It has to stand alone: who, what, why, what was tried and what you recommend."),

Q("d1s14", D, "standard", "Code generation with Claude Code",
  "A pull request touches 14 files. Reviewing them all in one pass gives detailed comments on some files and superficial ones on others, misses obvious bugs, and flags a pattern in one file while approving identical code in another. How should the review be restructured?",
  "Review each file in its own focused pass, then run a separate pass for cross-file data flows.",
  ["Run three independent full-PR passes and report only findings that appear in at least two of them.",
   "Move to a model with a larger context window so all 14 files fit comfortably in one attentive pass.",
   "Require developers to break large pull requests into submissions of three or four files each."],
  "The symptom is attention dilution across a wide input. Per-file passes restore consistent depth and an integration pass covers what they miss; a bigger window does not improve attention quality, and consensus voting suppresses real findings."),

Q("d1s15", D, "standard", "Developer productivity tools",
  "You have spent an hour with an agent mapping how a legacy billing module works, and now want to compare a Redux and a Context API rewrite without losing that investigation. What do you use?",
  "fork_session, which branches two independent lines of work from the shared investigation context.",
  ["Two fresh sessions, each given the same summary of the investigation as its opening prompt.",
   "--resume on the same session twice, so both explorations continue from the saved context.",
   "/compact followed by both questions in the same session, keeping the comparison in one place."],
  "fork_session exists precisely for branching from shared context. Resuming the same session twice gives you one interleaved thread, and starting fresh throws the investigation away."),

Q("d1s16", D, "standard", "Developer productivity tools",
  "You resume a three-day-old session with claude --resume audit-session. Several of the files it examined have been refactored since. What is the risk?",
  "The saved tool results describe the old code, and the agent has no way to know they are stale.",
  ["Resuming replays every tool call from the original session, so the refactor will be undone.",
   "The session cannot be resumed once the working tree has changed and will start empty instead.",
   "Resuming re-reads every file it touched, so the context immediately exceeds the window."],
  "A resumed session carries its saved tool results forward as if they were current. Where files have moved on, a fresh start from a written summary of the findings is usually more reliable."),

# ------------------------------------------------------------- challenging ---

Q("d1c01", D, "challenging", "Multi-agent research system",
  "Running the system on \"AI impact on the creative industries\", every subagent succeeds: searches return relevant articles, summaries are accurate, synthesis is coherent. Yet reports only ever cover visual art. Coordinator logs show three subtasks: \"AI in digital art\", \"AI in graphic design\", \"AI in photography\". What is the root cause?",
  "The coordinator's decomposition was too narrow, so whole areas of the topic were never assigned to anyone.",
  ["The document analysis agent's relevance criteria are too strict and filter out non-visual sources.",
   "The web-search agent's queries are not broad enough and should be widened across more sectors.",
   "The synthesis agent has no instruction to check the assembled findings for coverage gaps."],
  "Music, literature and film were never delegated, so no subagent could have found them. When every worker performs correctly, look at what was assigned before blaming execution."),

Q("d1c02", D, "challenging", "Multi-agent research system",
  "The synthesis agent frequently needs to verify a claim. Today it hands control back to the coordinator, which calls the web-search agent and re-invokes synthesis — two to three extra round trips and 40% more latency. Analysis shows 85% of those checks are simple facts (dates, names, figures) and 15% need real investigation.",
  "Give synthesis a narrow verify_fact tool for the simple checks, and keep complex verification routed through the coordinator.",
  ["Have the web-search agent cache extra context around every source during the initial research, anticipating what synthesis will need.",
   "Let the synthesis agent accumulate its verification needs and return them to the coordinator as one batch at the end.",
   "Give the synthesis agent the full web-search toolset so it can resolve any verification itself without a round trip."],
  "Least privilege applied to the 85% case: a narrow tool removes most of the round trips while the coordinator still mediates anything genuinely complex. Full access dissolves the separation of responsibilities, batching creates blocking dependencies between facts, and speculative caching cannot predict what will be questioned."),

Q("d1c03", D, "challenging", "Multi-agent research system",
  "On broad topics the web-search agent and the document analysis agent keep investigating the same subtopics. Token use nearly doubles with no gain in breadth or depth. What addresses this most effectively?",
  "Have the coordinator partition the research space before delegating, giving each agent distinct subtopics or source types.",
  ["Let both agents run in parallel as they do now and have the coordinator deduplicate the overlap before synthesis.",
   "Introduce shared state where each agent logs its current focus so the others can steer around it as they work.",
   "Serialise the two agents so document analysis runs after web search and can use its output to avoid repeats."],
  "The root cause is undefined boundaries, and boundaries are set at delegation time. Deduplicating afterwards has already paid for the wasted tokens, shared state adds coordination the hub topology deliberately avoids, and serialising sacrifices the parallelism."),

Q("d1c04", D, "challenging", "Agentic AI tools",
  "Your remove_team_member tool takes a dry_run boolean so impact can be previewed first. Monitoring shows the agent calling it with dry_run=false directly. Every removal must be preceded by a preview the user explicitly confirms. What is the most reliable design?",
  "Split it into preview_remove_member, which returns the impact plus a single-use confirmation token, and execute_remove_member, which requires that token.",
  ["Add server-side validation that accepts dry_run=false only if an identical dry_run=true call arrived within the last 60 seconds.",
   "Mark the tool as requiring confirmation and have the orchestration layer prompt the user before forwarding calls to it.",
   "Expand the tool description with instructions and examples requiring a dry_run=true call and a user confirmation first."],
  "Token binding makes the unsafe path unrepresentable: execution cannot happen without an artefact only the preview produces. A time window is a heuristic that a replayed call satisfies, an orchestration prompt depends on infrastructure outside the tool, and description text is an instruction, not a control."),

Q("d1c05", D, "challenging", "Customer support agent",
  "Metrics show the agent averaging more than four API round trips per resolution. Analysis shows it requests get_customer and lookup_order in separate consecutive turns even when it clearly needs both. What reduces the loop count most effectively?",
  "Instruct Claude to request all the tools it needs in a single turn and return every result together before the next call.",
  ["Add composite tools such as get_customer_with_orders that bundle the common lookup combinations into one call.",
   "Raise max_tokens so Claude has room to plan the whole investigation and combine its requests naturally.",
   "Speculatively execute the tools it is likely to need alongside whatever it requests and return all results."],
  "Claude can already emit several tool_use blocks in one turn; the prompt simply has not asked it to. Composite tools multiply the surface for every new combination, max_tokens does not govern batching, and speculative execution runs side effects nobody requested."),

Q("d1c06", D, "challenging", "Customer support agent",
  "Simple requests resolve in three or four tool calls with 91% success. Requests like \"I was billed twice, my discount didn't apply and I want to cancel\" average twelve or more calls at 54% success, working through the issues one at a time and re-fetching the same customer data for each. What change helps most?",
  "Decompose the request into separate issues and investigate them in parallel against one shared customer context, then synthesise a single resolution.",
  ["Add verification checkpoints between stages so the agent records progress on each issue before starting the next one.",
   "Add few-shot examples showing ideal tool-call sequences for a range of multi-part billing scenarios.",
   "Collapse get_customer, lookup_order and the billing tools into one investigate_issue tool to shorten the chain."],
  "Both symptoms — the call count and the redundant fetches — come from sequential handling with no shared context. Checkpoints formalise the sequence rather than removing it, examples do not change the shape of the work, and one god-tool hides the problem behind a coarser interface."),

Q("d1c07", D, "challenging", "Customer support agent",
  "When a customer's message contains the word \"account\", the agent calls get_customer first 78% of the time. Phrased without that word, the same request goes to lookup_order first 93% of the time. The tool descriptions are clear and unambiguous. What is the most likely cause?",
  "Keyword-sensitive routing instructions in the system prompt are steering tool choice on the presence of the word.",
  ["Tool descriptions need explicit negative examples saying when each tool should not be used, to counter the keyword pull.",
   "The model's pretraining associates account vocabulary with customer records strongly enough to override tool descriptions.",
   "The model has seen too few multi-concept messages and needs fine-tuning on examples that mix account and order language."],
  "A split that sharp and that systematic is a rule firing, not a tendency. With descriptions already clear, the remaining place a keyword can be wired to a tool is the prompt itself."),

Q("d1c08", D, "challenging", "Multi-agent research system",
  "A document analysis subagent fails regularly on PDFs: corrupted sections raise parse exceptions, some files are password-protected, and the parser occasionally hangs on very large ones. Today any exception ends the subagent and returns an error, so the coordinator is constantly deciding whether to retry, skip or fail. What is the right architectural change?",
  "Recover locally in the subagent for transient failures, and escalate only what it cannot resolve, with the steps attempted and any partial results.",
  ["Have the subagent always return a success status with partial results, putting error detail in metadata for the coordinator to inspect.",
   "Add a dedicated error-handling agent that watches a shared failure queue and sends restart instructions to subagents.",
   "Validate every document in the coordinator before delegation and reject the ones likely to fail parsing."],
  "Handle a failure at the lowest level that can actually resolve it, and escalate the rest with enough context to decide. Reporting failure as success hides it, a separate error agent adds a second coordination path, and pre-validating means predicting parser behaviour without parsing."),

Q("d1c09", D, "challenging", "Customer support agent",
  "On complex billing disputes and multi-order returns, satisfaction runs 15% below simple cases even when the resolution is technically right. The agent explains itself inconsistently — sometimes missing policy detail, sometimes timelines, sometimes next steps — and the gap differs case by case. No extra human review is available.",
  "Add a self-critique stage where the agent checks its draft against explicit completeness criteria before sending it.",
  ["Add few-shot examples showing complete explanations for five common complex cases, with policy context, timelines and next steps.",
   "Route complex cases to a larger model, using a defined complexity metric to decide which ones qualify.",
   "Add a closing confirmation step that asks the customer whether the reply fully resolved their issue."],
  "The gaps vary per case, so nothing fixed can enumerate them; an evaluator–optimizer pass checks each draft against the criteria instead. Examples cover the cases you thought of, a bigger model does not make completeness systematic, and asking the customer moves the work onto them."),

Q("d1c10", D, "challenging", "Claude Code for CI",
  "Non-obvious problems in generated code — optimisations that break edge cases, cleanups that change behaviour — are only caught when a human reviews the PR. Claude's own reasoning shows it considered those cases and concluded its approach was fine. What addresses the root cause?",
  "Run a second, independent Claude Code instance over the diff with no access to the generator's reasoning.",
  ["Enable extended thinking during generation so the model deliberates more thoroughly before committing to an approach.",
   "Add self-review instructions to the generation prompt, asking Claude to critique its suggestions before finalising.",
   "Put the full test files and module documentation in context so generation understands the expected behaviour better."],
  "The failure is confirmation bias: the generator already rationalised these cases and will rationalise them again. Only a reviewer that cannot see the reasoning gets the fresh-eyes effect that human peer review provides."),

Q("d1c11", D, "challenging", "Multi-agent research system",
  "You are writing the coordinator's system prompt for a research system whose topics vary widely from run to run. Which style produces the most reliable behaviour?",
  "State the goal and the quality criteria the final report must meet, and leave the decomposition to the coordinator.",
  ["Enumerate the steps in order — search, analyse, synthesise, write — so every run follows the same known-good path.",
   "Give one worked example of a complete run and instruct the coordinator to follow its structure each time.",
   "List the subagents available and the exact conditions under which each one must be invoked."],
  "A coordinator earns its cost by adapting the decomposition to the topic. Fixing the steps, the example or the invocation conditions turns it back into a pipeline, which is the cheaper pattern you would have chosen deliberately."),

Q("d1c12", D, "challenging", "Structured data extraction",
  "An agent maps an unfamiliar repository, then generates tests for whichever modules turn out to be untested. Halfway through it discovers an external payment dependency and adds a mocking step nobody specified. Which decomposition strategy does this describe, and is it appropriate?",
  "Dynamic adaptive decomposition — appropriate, because the subtasks only become knowable from intermediate results.",
  ["A fixed pipeline with an error branch — appropriate, since the mocking step is just recovery from an unexpected dependency.",
   "Dynamic adaptive decomposition — inappropriate here, because test generation is repeatable work that should be reproducible.",
   "Prompt chaining with a validation loop — appropriate, since each step validates the previous one before continuing."],
  "Nobody could have listed \"mock the payment provider\" before the discovery pass ran, which is exactly when adaptive decomposition is the right choice. A fixed pipeline is for work whose steps you can name in advance."),

Q("d1c13", D, "challenging", "Agentic AI tools",
  "Your agent runs against several MCP servers. Some return 40-field payloads where the task needs five fields, and the context window fills after a handful of calls. What is the cleanest structural fix?",
  "A PostToolUse hook that projects each tool result down to the fields the task actually uses before the model sees it.",
  ["Instructions in the system prompt telling the model to read only the relevant fields and ignore the rest of each payload.",
   "A larger-context model, so the verbose payloads stop exhausting the window during a normal run.",
   "A /compact pass whenever the context approaches its limit, summarising the accumulated tool output."],
  "The tokens are spent the moment the payload enters the context, so the fix has to happen before that. Telling the model to ignore fields does not stop them being counted, a larger window postpones the same problem, and compaction pays the cost first and then compresses it."),

Q("d1c14", D, "challenging", "Agentic AI tools",
  "Your agent loop appends the assistant message, then inspects stop_reason. In production it occasionally stops mid-investigation with no error and an incomplete answer. Logs show stop_reason was \"max_tokens\". How should the loop handle that?",
  "Treat it as truncation, not completion: the turn was cut off, so continue rather than returning it as a result.",
  ["Treat it like end_turn, since the model produced everything the token budget allowed for that answer.",
   "Retry the identical request unchanged, because max_tokens is a transient condition on the server side.",
   "Abort the run and surface an error, since a truncated turn leaves the conversation in an unusable state."],
  "Only end_turn means the work is finished. max_tokens says the output was cut short, so the loop must handle the truncation — usually by continuing — instead of presenting a partial answer as the result."),

Q("d1c15", D, "challenging", "Multi-agent research system",
  "You are writing the AgentDefinition for a synthesis subagent that merges findings and writes the report. Which allowed_tools list is right?",
  "Only what synthesis needs — the report-writing tool and a narrow fact-check tool — with everything else left out.",
  ["The same tools as the coordinator, so it can fetch anything a gap in the findings turns out to require.",
   "No tools at all, since a synthesis agent works purely from the text the coordinator passes it.",
   "Every read-only tool in the system, since reading cannot cause side effects and widens what it can verify."],
  "Least privilege: give a subagent the narrow set its job needs. Coordinator-level access breaks the separation of responsibilities, read-only access still lets it wander into work that belongs to other agents, and a fact-check need is real enough that no tools at all is too tight."),

Q("d1c16", D, "challenging", "Developer productivity tools",
  "A team proposes replacing a working single agent with a coordinator and four subagents, because \"multi-agent is more scalable\". The task is a linear document-processing job whose five steps always run in the same order. What is the strongest argument against?",
  "The work has no independent subtasks and no need for isolated context, so the coordination overhead buys nothing.",
  ["Multi-agent systems cannot guarantee ordering, so the five steps might execute out of sequence.",
   "Subagents cannot share the document between them, so each one would have to re-read it from disk.",
   "The coordinator would become a single point of failure that the current single-agent design avoids."],
  "Multi-agent pays for itself when subtasks are genuinely independent or need separate context. A fixed linear sequence has neither, so you take the latency and token cost of delegation for nothing."),

# --------------------------------------------------------------- practical ---
# From the practical test. Paper E only — see emit.py.

Q("d1p01", D, "standard", "Multi-agent research system",
  "The document analysis subagent reaches a PDF it cannot parse. You are designing how that failure is handled. What should the subagent do with it?",
  "Return an error to the coordinator with the context around it, and let the coordinator decide how to proceed.",
  ["Skip the corrupted document silently and carry on with the rest, so the workflow is never interrupted.",
   "Retry the parse three times with exponential backoff before reporting the failure upstream at all.",
   "Raise an exception that terminates the whole research workflow, since the input set is incomplete."],
  "The coordinator is the only part of the system placed to choose between skipping the file, trying another parser and telling the user, and it can only choose if it is told. Silence hides a gap in the evidence, backoff cannot repair a corrupt file, and ending the run throws away everything that succeeded.",
  pool="practical"),
