# -*- coding: utf-8 -*-
from common import Q

D = 1  # D2 — Tool Design & MCP Integration

# ---------------------------------------------------------------- standard ---

Q("d2s01", D, "standard", "Customer support agent",
  "Logs show the agent calling get_customer when users ask about orders. Both tools carry minimal descriptions — \"Gets customer information\" and \"Gets order details\" — and accept similar-looking identifiers. What is the most effective first step?",
  "Expand each description with input formats, example queries, edge cases and the boundary against the similar tool.",
  ["Add five to eight few-shot examples to the system prompt routing order questions to lookup_order.",
   "Merge them into one lookup_entity tool that takes any identifier and picks the backend internally.",
   "Add a routing layer that inspects the message and preselects a tool from keywords and id patterns."],
  "The description is the model's primary selection mechanism, so a thin description is the root cause and the cheapest thing to fix. Examples, merging and routing layers all add machinery around a gap you have not closed."),

Q("d2s02", D, "standard", "Agentic AI tools",
  "You are writing the description for a tool that cancels a subscription. Which content belongs in it?",
  "What the tool does, when to use it, when not to, the expected input format and a worked example.",
  ["A precise description of the return payload, since that is what the model has to parse afterwards.",
   "The implementation notes and the downstream service it calls, so the model can reason about failures.",
   "A short label only — long descriptions consume context on every request without improving selection."],
  "The description is documentation written for a model deciding whether to call this tool. Purpose, boundaries, input shape and an example are what that decision needs; implementation detail is not, and brevity here costs accuracy."),

Q("d2s03", D, "standard", "Agentic AI tools",
  "Two MCP servers are connected. One exposes analyze_content described as \"analyzes content and extracts key information\", the other analyze_document described as \"analyzes documents and extracts key information\". Requests are misrouted about 45% of the time. What is wrong?",
  "The two descriptions overlap semantically, so nothing in them distinguishes the tools from each other.",
  ["Two MCP servers cannot expose tools with similar names without a namespace prefix to separate them.",
   "The model always prefers the tool listed first when several plausibly match the request.",
   "Content analysis and document analysis need a routing classifier, because descriptions alone never disambiguate."],
  "Selection is made from the descriptions, and these two say the same thing. Rename and rewrite them so each states what it is for and what it is not for; the ambiguity is the bug."),

Q("d2s04", D, "standard", "Agentic AI tools",
  "Which of these is a Model Context Protocol resource rather than a tool?",
  "A database schema the agent can read for context.",
  ["A function that inserts a row into that database.",
   "A saved prompt template for a recurring analysis task.",
   "A hook that fires after a tool returns and rewrites its output."],
  "MCP exposes tools (functions the agent calls to act), resources (data it reads for context) and prompts (reusable templates). A schema is data to read, so it is a resource; hooks belong to the Agent SDK, not MCP."),

Q("d2s05", D, "standard", "Code generation with Claude Code",
  "Six developers each have their own GitHub token. You want one shared MCP server configuration in the repository without committing any credential. What do you do?",
  "Add the server to the project .mcp.json using environment variable substitution for the token, and document the variable.",
  ["Have each developer add the server themselves with claude mcp add --scope user and their own token.",
   "Commit the server with a placeholder token and tell developers to override it in their local configuration.",
   "Write a wrapper server that reads tokens from a .env file and proxies the GitHub API, and commit the wrapper."],
  "A project .mcp.json with ${GITHUB_TOKEN} is one version-controlled source of truth while the secret stays in each developer's environment. Per-user setup drifts, a placeholder is a committed value waiting to be used, and a proxy is a component to maintain for nothing."),

Q("d2s06", D, "standard", "Agentic AI tools",
  "A search tool fails because the query syntax is invalid. What should it return to the agent?",
  "A structured error naming the category, whether a retry could help, and what about the input was wrong.",
  ["An empty result set, so the agent treats the search as having found nothing and moves on.",
   "A raised exception, so the failure surfaces in your logs with a full stack trace attached.",
   "A generic \"search unavailable\" string, keeping failure handling uniform across every tool."],
  "The agent can only recover from what it can read. A category, a retryable flag and the specific problem let it fix the query; an empty result is a lie, and a generic string or an exception discards the information needed to act."),

Q("d2s07", D, "standard", "Structured data extraction",
  "An extraction schema marks customer_email as required. Many source documents genuinely have no email address. What happens, and what should you do?",
  "The model invents plausible addresses to satisfy the schema; mark the field optional or nullable instead.",
  ["Extraction fails validation on those documents; add a retry loop that re-runs them with a longer prompt.",
   "The field comes back as an empty string; add post-processing that converts empty strings to null.",
   "The document is skipped entirely; add a pre-filter that routes documents without an email elsewhere."],
  "Marking a field required tells the model the value is always present, so it supplies one. Required is for information that genuinely always exists; anything else is optional, or typed to allow null."),

Q("d2s08", D, "standard", "Structured data extraction",
  "Your document_type enum lists invoice, receipt, contract and purchase_order. Production documents include delivery notes and credit memos, which the model forces into the nearest category. What is the standard fix?",
  "Add an \"other\" member paired with a free-text detail field so the real type survives.",
  ["Drop the enum and let the field be free text, since the closed set is what is causing the loss.",
   "Extend the enum with every document type seen so far and redeploy whenever a new one appears.",
   "Add a confidence score to the field so downstream code can discard low-confidence classifications."],
  "An enum plus \"other\" with a detail string keeps the categories useful while letting data outside them come through intact. Free text loses the structure, and chasing the list keeps you one document behind."),

Q("d2s09", D, "standard", "Developer productivity tools",
  "An agent has both the built-in Read and Grep tools and an MCP server exposing similar file-search tools. It keeps using the built-in ones and ignoring the MCP server. What does this tell you?",
  "Agents tend to reach for built-in tools over MCP tools with overlapping purpose, so the MCP descriptions must state what only they can do.",
  ["MCP tools are only consulted once the built-in tools have failed, which is the documented precedence order.",
   "Built-in tools are cheaper to call, so the model's selection is optimising for token cost.",
   "The MCP server is misconfigured; correctly registered tools are ranked ahead of built-ins."],
  "There is no precedence rule to fix here. Where two tools plausibly answer the same request, the familiar built-in wins unless the description makes the MCP tool's distinct value explicit."),

Q("d2s10", D, "standard", "Multi-agent research system",
  "The document analysis agent was given a general-purpose fetch_url tool so it could download documents. Logs show it now fetches search engine result pages to do ad-hoc web searching, which belongs to another agent. What is the most effective fix?",
  "Replace fetch_url with a load_document tool that validates the URL points at a document format.",
  ["Add a filter that blocks fetch_url calls to known search engine domains and allows the rest.",
   "Remove fetch_url and route every URL retrieval through the coordinator to the web-search agent.",
   "Add a line to the agent's prompt stating that fetch_url is for document URLs and not for searching."],
  "Constrain the capability at the interface and the unwanted behaviour stops being possible. A domain blocklist chases hostnames forever, routing everything through the coordinator removes a capability the agent legitimately needs, and prompt wording only discourages."),

# ------------------------------------------------------------- challenging ---

Q("d2c01", D, "challenging", "Conversational AI architecture",
  "search_catalog fails 12% of the time: 8% are network timeouts that succeed on retry, 4% are query syntax errors that never will. Both come back identically today, so the agent retries everything. How should the tool's error handling change?",
  "Retry transient timeouts inside the tool with backoff, and return syntax errors immediately with the validation detail.",
  ["Return every error with a retryable boolean and a type field, leaving the retry decision to the agent.",
   "Apply exponential backoff uniformly to all failures, so transient errors recover and the rest fail slower.",
   "Add few-shot examples to the system prompt teaching the agent to tell network errors from syntax errors."],
  "The tool is the only component that knows which failure it hit, so it is the right place to retry. Handing the agent a flag makes a deterministic decision probabilistic, uniform backoff wastes time on errors that cannot succeed, and prompt examples ask the model to infer what the tool already knows."),

Q("d2c02", D, "challenging", "Customer support agent",
  "get_customer returns every match when searching by name. When there are several, Claude currently picks the one with the most recent order — which is the wrong account 15% of the time. How should you address this?",
  "Have Claude ask for a second identifier — email, phone or order number — before taking any action on an ambiguous match.",
  ["Change get_customer to rank the matches and return only the most likely one, so the ambiguity never reaches the model.",
   "Score the agent's confidence and let it act above 85%, asking for clarification only below that threshold.",
   "Add few-shot examples showing correct reasoning and tool sequencing when a name lookup returns several accounts."],
  "The customer knows which account is theirs, and one extra turn is cheap next to a 15% misidentification rate. Ranking inside the tool hides the ambiguity rather than resolving it, and self-rated confidence is unreliable exactly where the accounts look alike."),

Q("d2c03", D, "challenging", "Structured data extraction",
  "Your extraction tool's JSON Schema is correct, but around 6% of responses still include a field with the wrong type. You already retry on validation failure. How should the retry be constructed?",
  "Send back the document, the invalid extraction and the specific validation error, and ask for a corrected result.",
  ["Re-send the original request unchanged, since the failure is sampling variance and a second attempt usually succeeds.",
   "Re-send with a lower temperature and a stricter instruction to follow the schema exactly this time.",
   "Re-send with the schema repeated in the user turn as well as in the tool definition, to reinforce the contract."],
  "A repair attempt needs to know what went wrong; the validation error is the whole point. An identical retry relies on luck, and reinforcing the schema addresses a misunderstanding the model did not have."),

Q("d2c04", D, "challenging", "Agentic AI tools",
  "A tool returns isError: true with the message \"Request failed\". The agent retries it eleven times before giving up, burning the token budget. What is the underlying design problem?",
  "The error carries no category and no retryable signal, so the agent cannot tell a permanent failure from a transient one.",
  ["isError is being used for a condition that is not an error, and the tool should return a normal result instead.",
   "The agent is missing an iteration cap, which is what should have terminated the retry sequence.",
   "Retries belong in the agent loop rather than in the model's hands, so the tool result is the wrong place to signal failure."],
  "An error the model cannot classify is one it will keep probing. Category, retryability and a concrete description are what turn a failure into a decision; an iteration cap would only have hidden the same defect sooner."),

Q("d2c05", D, "challenging", "Developer productivity tools",
  "You are adding an MCP server that exposes 30 tools covering an entire ticketing platform. After connecting it, the agent's tool selection accuracy on its original tasks drops noticeably. What is the most likely explanation?",
  "Thirty extra definitions crowd the selection space and overlap the existing tools, making every choice harder.",
  ["Thirty tool definitions exceed the per-request tool limit, so some are silently dropped from the request.",
   "MCP tools are evaluated after built-in tools, so adding them re-orders and destabilises the existing selection.",
   "The server's tools are being cached between requests, so the model sees a stale definition list."],
  "Every tool definition is context the model weighs on every request. A large, partly overlapping surface degrades selection, which is why you expose the tools an agent actually needs rather than the whole platform."),

Q("d2c06", D, "challenging", "Customer support agent",
  "process_refund currently takes (customer_id, order_id, amount, reason, notify_customer, refund_method, partial, currency, approver_id, idempotency_key). Agents frequently supply wrong or contradictory combinations. What is the best redesign?",
  "Split it into the few narrow operations the workflow actually performs, each with the minimum arguments that operation needs.",
  ["Mark most of the parameters optional with documented defaults, so a call only needs customer_id, order_id and amount.",
   "Keep the signature and add an extensive description explaining every valid combination of parameters.",
   "Add a validation layer that rejects invalid combinations and returns an error explaining the correct usage."],
  "One tool per job with a small argument list is the principle; ten parameters means several jobs wearing one name. Optional parameters and documentation leave the combinatorics in place, and validation only reports the confusion after the fact."),

Q("d2c07", D, "challenging", "Structured data extraction",
  "Extraction must classify a document's sentiment, but some documents genuinely give no basis for a judgement. Today the model picks a category anyway. Which schema change best reflects reality?",
  "Add an \"unclear\" enum member so the model can report honestly that the document does not support a classification.",
  ["Make the field nullable, so the model returns null whenever it cannot classify the document.",
   "Add a confidence score alongside the category and discard classifications below a threshold downstream.",
   "Split the field into positive, negative and neutral booleans, so the model can leave all three false."],
  "An explicit \"unclear\" value gives the model a correct answer to choose, which is what stops it guessing. Null conflates \"absent\" with \"undeterminable\", and both the score and the booleans still ask for a judgement first and filter afterwards."),

Q("d2c08", D, "challenging", "Agentic AI tools",
  "A tool that queries three source categories reports \"0 results\" from industry databases and \"Connection timeout\" from the patent database. What must the tool's return distinguish, and why?",
  "An access failure from a valid empty result — one needs a retry decision, the other is a finding.",
  ["A partial success from a total failure, so the coordinator knows whether any category returned data at all.",
   "A transient from a permanent failure, so only the transient ones are retried automatically inside the tool.",
   "A query error from a data error, so the coordinator knows whether to fix the query or accept the answer."],
  "\"No patents exist\" and \"we could not reach the patent database\" are different facts about the world. Collapsing them either discards a real finding or hides an outage behind an empty list."),

Q("d2c09", D, "challenging", "Code generation with Claude Code",
  "Your project .mcp.json is committed and correct, but one developer's Claude Code keeps connecting to a stale local instance of the same server. What explains it, and what is the right response?",
  "A personal configuration is overriding the project entry for that server; they should remove or repoint their own override.",
  ["The project file is only read on first launch, so they need to restart Claude Code to pick up the committed entry.",
   "Server entries are merged by transport rather than by name, so two entries for one server both stay active.",
   "Project configuration needs an explicit priority field to take precedence over a developer's local entry."],
  "Personal configuration takes precedence over project configuration for the same server name — which is the point, since it is what lets a developer point at a local build. Here that override has simply outlived its purpose."),

Q("d2c10", D, "challenging", "Multi-agent research system",
  "You are designing tools for a synthesis agent that must attribute every claim. Which tool contract best supports that?",
  "Retrieval tools that return the quote, the source URL and the publication date alongside the extracted claim.",
  ["Retrieval tools that return clean prose summaries, with the source list appended once at the end of the response.",
   "A single tool that returns the full source document, leaving the synthesis agent to quote and attribute from it.",
   "Retrieval tools that return the claim plus a numeric relevance score the report can cite as a confidence level."],
  "Attribution is lost during summarisation unless the claim-to-source mapping travels with the claim. Dates matter too — without them a temporal difference reads as a contradiction. Appended source lists and relevance scores do not tell you which claim came from where."),
