# -*- coding: utf-8 -*-
from common import Q

D = 2  # D3 — Claude Code Configuration & Workflows

# ---------------------------------------------------------------- standard ---

Q("d3s01", D, "standard", "Code generation with Claude Code",
  "You want a custom /review command running your team's review checklist, available to every developer as soon as they clone the repository. Where does the command file go?",
  "In .claude/commands/ inside the project repository.",
  ["In ~/.claude/commands/ on each developer's machine, kept in sync by the onboarding script.",
   "In the root CLAUDE.md, as a section describing the review checklist and its trigger.",
   "In .claude/config.json, as an entry in the array of project command definitions."],
  "Project commands live in .claude/commands/, so they are version-controlled and arrive with the clone. The home directory is for personal commands, CLAUDE.md holds instructions rather than command definitions, and there is no commands array in a config file."),

Q("d3s02", D, "standard", "Code generation with Claude Code",
  "You have to break a monolith into microservices: dozens of files, and real decisions about service boundaries and module dependencies. How should you approach it?",
  "Use planning mode to explore the codebase and the dependencies and design the approach before editing anything.",
  ["Execute directly and incrementally, letting the natural service boundaries emerge from the refactor as it goes.",
   "Execute directly with detailed up-front instructions specifying the structure of each service you want.",
   "Execute directly and switch into planning mode at the point where the complexity becomes hard to manage."],
  "Planning mode is built for large changes with several viable approaches and architectural consequences. Direct execution risks expensive rework, detailed instructions assume you already know the structure you are trying to discover, and switching late means the rework has already happened."),

Q("d3s03", D, "standard", "Code generation with Claude Code",
  "Conventions differ across your codebase — React components, API handlers, database models — and test files sit next to the code they test rather than in one directory. You want the right conventions applied automatically. What do you use?",
  "Rule files under .claude/rules/ with YAML frontmatter declaring glob patterns for the paths each rule covers.",
  ["A CLAUDE.md in every subdirectory, each holding the conventions for the code beneath it.",
   "One root CLAUDE.md with a section per area, relying on Claude to infer which section applies.",
   "A skill per code type under .claude/skills/, each embedding the conventions for that type."],
  "Path-scoped rules match on the file being touched, which is exactly what you need when the relevant files are scattered. Nested CLAUDE.md files do not help when tests sit beside dozens of different areas, inference is unreliable, and skills load on demand rather than automatically."),

Q("d3s04", D, "standard", "Claude Code for CI",
  "Your pipeline runs claude \"Analyze this pull request for security issues\" and the job hangs. Logs show it waiting for interactive input. What is the correct invocation?",
  "claude -p \"Analyze this pull request for security issues\"",
  ["CLAUDE_HEADLESS=true claude \"Analyze this pull request for security issues\"",
   "claude \"Analyze this pull request for security issues\" < /dev/null",
   "claude --batch \"Analyze this pull request for security issues\""],
  "-p (or --print) is the documented non-interactive mode: it processes the prompt, writes to stdout and exits. The others are either a Unix workaround for a problem the flag solves properly, or flags and variables that do not exist."),

Q("d3s05", D, "standard", "Code generation with Claude Code",
  "Three developers report that Claude follows the guidance \"always include comprehensive error handling\". A fourth, who joined last week, says it does not. All four work in the same repository with current code. What is the cause and the fix?",
  "The guidance is in the original developers' user-level CLAUDE.md files; move it to the project-level file.",
  ["The new developer's user-level CLAUDE.md contains a conflicting instruction; they should remove that section.",
   "CLAUDE.md is cached after first read and the original developers are on a stale copy; everyone should clear the cache.",
   "Claude Code adapts to each developer over time; the new joiner needs to restate the requirement until it holds."],
  "Guidance that only some team members receive was never committed. Project-level configuration is what makes a convention shared, and it reaches every current and future member of the team automatically."),

Q("d3s06", D, "standard", "Code generation with Claude Code",
  "A /analyze-codebase skill runs a deep analysis — dependency scanning, coverage counts, quality metrics. Afterwards the session becomes sluggish and Claude loses track of the original task. What do you change, keeping the analysis intact?",
  "Add context: fork to the skill's frontmatter so it runs in an isolated subagent context.",
  ["Add model: haiku to the frontmatter so the analysis runs on a faster, cheaper model.",
   "Split it into three smaller skills so each one returns a more manageable amount of output.",
   "Instruct the skill to compress its results into a short summary before it displays anything."],
  "The analysis output is filling the main context window. context: fork runs it elsewhere and returns only the result, so the main session keeps the task it started with; the other options shrink the output without moving it."),

Q("d3s07", D, "standard", "Code generation with Claude Code",
  "The team has a /commit skill at .claude/skills/commit/SKILL.md. One developer wants their own message format and extra checks without affecting anyone else. What do you recommend?",
  "Create ~/.claude/skills/commit/SKILL.md with the same name, which takes precedence for that developer.",
  ["Create a personal skill under a different name such as /my-commit, leaving the project one untouched.",
   "Set override: true in the personal skill's frontmatter so it outranks the project version.",
   "Add conditional logic to the project skill's frontmatter that branches on the developer's username."],
  "Personal skills take precedence over project skills with the same name, so the override is the mechanism and the familiar command name survives. A second name works but costs the muscle memory, there is no override flag, and branching on usernames puts personal preferences in the shared repository."),

Q("d3s08", D, "standard", "Code generation with Claude Code",
  "Your CLAUDE.md has passed 500 lines, mixing TypeScript conventions, testing guidance, API patterns and deployment steps. Developers struggle to find and update the right section. What does Claude Code support for this?",
  "Separate Markdown files under .claude/rules/, one per topic, such as testing.md and api-conventions.md.",
  ["A .claude/config.yaml that maps file patterns onto named sections within the existing CLAUDE.md.",
   "README.md files in the relevant subdirectories, which Claude loads as instructions for that area.",
   "Several CLAUDE.md files down the directory tree, each one replacing its parent's instructions."],
  "A .claude/rules/ directory is the supported way to break a large instruction set into focused modules. There is no section-mapping config file, README.md is not an instruction source, and nested CLAUDE.md files compose rather than override."),

Q("d3s09", D, "standard", "Claude Code for CI",
  "CI reviews are substantive, but findings come back as prose paragraphs that somebody has to copy into pull request comments by hand. You want each finding posted inline, which needs a file path, line number, severity and suggested fix. What is the most effective approach?",
  "Run the CLI with --output-format json and --json-schema, then parse the result and post the comments through the API.",
  ["Add an output-format section to CLAUDE.md with examples of the structured findings you expect.",
   "Put a parseable template in the review prompt, such as [FILE:path] [LINE:n] [SEVERITY:level].",
   "Keep the prose review and add a second call that turns it into a JSON summary of the findings."],
  "The CLI has flags for exactly this, and they constrain the output rather than requesting it. Project context and prompt templates produce mostly-valid output, and a second summarisation pass adds a call and a new place to lose detail."),

Q("d3s10", D, "standard", "Developer productivity tools",
  "You are adding wrappers around external API calls across 120 files. Phase one discovers every call site, phase two designs the approach with you, phase three implements it. Phase one alone floods the context window with call sites before discovery finishes. What do you do?",
  "Run phase one in an Explore subagent so the verbose discovery stays isolated and only a summary comes back.",
  ["Run everything in the main conversation and use /compact periodically as the context fills up.",
   "Define the pattern in CLAUDE.md and work through the files in batches across several sessions.",
   "Switch to headless mode with --continue, passing explicit context summaries between batched calls."],
  "Delegating discovery keeps the verbose output out of the main window, which is where the design and implementation phases need their context. Compaction pays for the tokens first, and both batching options fragment the collaborative phase."),

Q("d3s11", D, "standard", "Code generation with Claude Code",
  "Which statement about the CLAUDE.md hierarchy is correct?",
  "User, project and directory-level files all apply, with the more specific file layering on top of the broader ones.",
  ["Only the most specific CLAUDE.md applies; a directory-level file replaces the project file entirely.",
   "Only the project-level file is loaded automatically; user and directory files must be imported explicitly.",
   "The user-level file wins over the project file, so personal conventions always override team ones."],
  "The levels compose rather than compete: user-level for personal defaults, project-level for shared conventions, directory-level for local specifics. That is why a convention only the team should share has to be committed at project level."),

Q("d3s12", D, "standard", "Developer productivity tools",
  "A long investigation session is approaching its context limit but the work is not finished. Which built-in mechanism reduces context usage without abandoning the session?",
  "/compact, which condenses the accumulated history so the session can continue.",
  ["--resume, which reloads the session from its last saved checkpoint with a smaller context.",
   "fork_session, which starts a branch carrying only the most recent exchanges.",
   "context: fork, which moves the existing history into an isolated subagent."],
  "/compact is the in-session compression mechanism. --resume reopens a session later, fork_session branches a line of work from shared context, and context: fork is skill frontmatter rather than something you invoke mid-session."),

# ------------------------------------------------------------- challenging ---

Q("d3c01", D, "challenging", "Code generation with Claude Code",
  "CLAUDE.md has grown past 400 lines: coding standards, testing conventions, a PR review checklist, deployment instructions and migration procedures. Standards and testing conventions must always apply; the other three only during those tasks. How do you restructure it?",
  "Keep the universal standards in CLAUDE.md and move review, deployment and migrations into skills with trigger keywords.",
  ["Split the whole file into .claude/rules/ entries with glob patterns so each part loads for the relevant file types.",
   "Move everything into skills organised by workflow, leaving CLAUDE.md as a short project description.",
   "Keep everything in CLAUDE.md but use import syntax to split it into separately maintained files by category."],
  "CLAUDE.md loads every session, which is what \"always applies\" requires; skills load when their trigger appears, which is what the other three need. Path globs key off files rather than tasks, moving everything out loses the always-on guarantee, and imports reorganise the file without changing when it loads."),

Q("d3c02", D, "challenging", "Code generation with Claude Code",
  "A /migration skill takes a name through $ARGUMENTS. In production: developers often run it with no argument and get badly named files; it sometimes reuses schema details from unrelated earlier conversations; and one developer triggered a destructive cleanup because the skill had broad tool access. Which configuration fixes all three?",
  "argument-hint in the frontmatter, context: fork for isolation, and allowed-tools narrowed to file writes.",
  ["Positional $1 and $2 parameters, explicit schema file references for context, and a frontmatter warning about destructive operations.",
   "Validation instructions for the argument, a prompt line telling it to ignore earlier conversation, and a list of prohibited operations.",
   "A split into /migration-create and /migration-apply, a prompt for the name when missing, and different tool scopes per skill."],
  "Three problems, three configuration features: argument-hint prompts for the input, context: fork keeps earlier conversation out, and allowed-tools makes the destructive call impossible. The alternatives solve at least one of them with instructions, which is exactly what failed."),

Q("d3c03", D, "challenging", "Code generation with Claude Code",
  "Two or three full endpoint implementations in context noticeably improve consistency when generating new endpoints — but that context is useless when debugging or reviewing in the same directory. Which configuration is most effective?",
  "A skill that references the examples and the pattern instructions, invoked on demand through its slash command.",
  ["Path-specific rules under .claude/rules/api/ that include the examples whenever work happens in the API directory.",
   "The examples and pattern documentation in the project CLAUDE.md so they are always available when needed.",
   "Referencing the examples by hand in each generation request, pasting the code into the prompt."],
  "The distinction here is the task, not the path: the same directory hosts generation, debugging and review. A skill loads when you ask for it; path rules would load the examples for all three, and CLAUDE.md for every session."),

Q("d3c04", D, "challenging", "Code generation with Claude Code",
  "An /explore-alternatives skill helps the team weigh implementation options. Developers report that afterwards Claude keeps referring back to rejected approaches and carrying exploration context into the actual implementation. How do you configure it?",
  "Add context: fork to the skill's frontmatter.",
  ["Split it into /explore-start and /explore-end to mark where exploration context should be discarded.",
   "Move the skill to ~/.claude/skills/ so its context is kept separate from the project session.",
   "Use the shell prefix inside the skill so the exploration runs as a subprocess outside the conversation."],
  "context: fork runs the skill in an isolated context, so the brainstorming never enters the main conversation history. Boundary markers do not remove what has already been added, and where a skill lives has no bearing on which context it uses."),

Q("d3c05", D, "challenging", "Claude Code for CI",
  "Your CI runs three Claude analyses: fast style checks that block merges, weekly full-codebase security audits, and nightly test generation for changed modules. The Message Batches API is 50% cheaper but can take up to 24 hours. Which mapping is correct?",
  "Synchronous calls for the blocking style checks; the Batches API for the weekly audits and the nightly test generation.",
  ["Synchronous calls for the style checks and the nightly test generation; the Batches API only for the weekly audits.",
   "The Batches API for all three, with the pipeline polling for completion before it reports results.",
   "Synchronous calls for all three, relying on prompt caching to bring the cost down instead."],
  "The deciding factor is whether anyone is waiting. Style checks block a merge, so they need a synchronous response; a weekly audit and an overnight job both tolerate a 24-hour window comfortably, and leaving the nightly run synchronous forfeits half its cost for nothing."),

Q("d3c06", D, "challenging", "Claude Code for CI",
  "Your review component is iterative: Claude analyses the changed file and may call a tool to request related files — imports, base classes, tests — before giving feedback. You are considering the Message Batches API to cut cost. What is the primary technical obstacle?",
  "A batch request cannot pause mid-flight to execute a tool and feed the result back, so the loop cannot run.",
  ["The 24-hour turnaround is too slow for pull request feedback, though the workflow would otherwise work as it does now.",
   "Batch requests do not accept tool definitions in their parameters, so the tool could not be offered at all.",
   "Batch results carry no correlation identifier, so outputs cannot be matched back to the requests that produced them."],
  "The Batches API is fire-and-forget: there is no point at which your code intercepts a tool call and returns a result. Latency is a real constraint too, but the workflow would not function at any latency, and custom_id exists precisely for correlation."),

Q("d3c07", D, "challenging", "Code generation with Claude Code",
  "You need Slack added as a notification channel. Email, SMS and push already follow an established pattern, but Slack offers incoming webhooks (simple, one-way), bot tokens (delivery confirmation and programmatic control) or a Slack App (two-way events, needs workspace approval). The ticket says \"add Slack support\" and nothing else. How do you start?",
  "Enter planning mode, explore the three integration options and their implications, and agree an approach before implementing.",
  ["Execute directly with incoming webhooks, matching the one-way pattern the existing channels already use.",
   "Execute directly with bot tokens, since that is the only option that leaves delivery confirmation available later.",
   "Execute directly by scaffolding a Slack channel class from the existing pattern and deciding the mechanism later."],
  "Several valid approaches with materially different architecture, and requirements that do not choose between them, is the definition of a planning-mode task. Each direct-execution option silently commits you to an answer the ticket never gave."),

Q("d3c08", D, "challenging", "Developer productivity tools",
  "A teammate argues that everything in .claude/rules/ could live in CLAUDE.md, since Claude will work out what is relevant. What is the strongest technical counter-argument?",
  "Rules with path globs apply deterministically to the files being touched, instead of relying on the model to infer relevance.",
  ["Rules files are loaded lazily, so they keep the session's initial context smaller than one large CLAUDE.md.",
   "CLAUDE.md is capped in size, so guidance beyond that limit has to live in rules files anyway.",
   "Rules can be overridden per developer, whereas CLAUDE.md applies identically to everyone on the team."],
  "The argument is about determinism: a glob either matches the file or it does not, while a section in a long file depends on the model noticing it applies. Claude Code does not enforce a size cap, and both mechanisms have the same personal-override story."),

Q("d3c09", D, "challenging", "Claude Code for CI",
  "Automated reviews average 15 findings per PR with a 40% false-positive rate. Developers say the bottleneck is investigation: each finding must be opened to read the reasoning before deciding. CLAUDE.md already documents acceptable patterns, and stakeholders have ruled out filtering findings before developers see them.",
  "Require each finding to carry its rationale and a confidence estimate inline, so developers can triage without opening it.",
  ["Add a post-processor that suppresses findings matching historical false-positive signatures automatically.",
   "Configure the reviewer to surface only high-confidence findings and hold the uncertain ones back.",
   "Split findings into blocking issues and suggestions, with different review requirements for each level."],
  "The constraint rules out anything that removes findings from view, so the only lever left is making each one faster to judge. Two of the alternatives filter, which is excluded; categorising by severity does not tell a developer whether a given finding is real."),

Q("d3c10", D, "challenging", "Claude Code for CI",
  "False-positive rates by category: security and correctness 8%, performance 18%, style and naming 52%, documentation 48%. Surveys show developers dismissing findings unread because \"half are wrong\", and the noisy categories are eroding trust in the accurate ones. What best restores trust?",
  "Turn off the high-false-positive categories for now, keep the precise ones running, and improve their prompts before re-enabling.",
  ["Leave every category on but show a confidence score with each finding so developers can decide what to look at.",
   "Leave every category on and add few-shot examples over the coming weeks to lift accuracy in the weak ones.",
   "Reduce strictness uniformly across all categories to bring the overall false-positive rate down."],
  "Trust is being destroyed faster than accuracy can be improved, so the noise has to stop now while the precise categories keep delivering. The other options all leave the 52% category in front of developers while you work."),

Q("d3c11", D, "challenging", "Claude Code for CI",
  "The first review round posts 12 findings. A developer pushes fixes, the review re-runs and posts 8 — five of which repeat comments on code that has since been fixed. How do you remove the redundancy without weakening the review?",
  "Put the previous findings in context and instruct Claude to report only new or still-unresolved issues.",
  ["Add a post-processing filter that drops findings matching earlier ones by file path and description.",
   "Limit the review to files changed in the most recent push, leaving earlier commits out of scope.",
   "Review only at PR creation and immediately before merge, skipping the intermediate commits."],
  "Deciding whether a finding still applies is a judgement about the current code, which is what Claude is for — but only if it can see what was already reported. String matching cannot tell a fixed issue from a recurring one, and both scope reductions trade thoroughness for quiet."),

Q("d3c12", D, "challenging", "Claude Code for CI",
  "Review-generated test suggestions are useful but roughly 60% duplicate scenarios the existing suite already covers. What most effectively reduces the duplicates?",
  "Put the existing test file in context so Claude can see which scenarios are already covered.",
  ["Ask for five suggestions instead of ten, on the basis that the most valuable cases come first.",
   "Instruct it to propose only edge cases and error conditions rather than success paths.",
   "Post-process the suggestions, dropping any whose description overlaps an existing test name."],
  "Claude cannot avoid duplicating tests it has never seen. Fewer suggestions just means fewer of both kinds, restricting it to edge cases discards valid new coverage, and name overlap is a poor proxy for scenario overlap."),

# --------------------------------------------------------------- practical ---
# From the practical test. Paper E only — see emit.py.

Q("d3p01", D, "challenging", "Claude Code for CI",
  "Two workflows run on synchronous calls: a pre-merge check that blocks the merge until it finishes, and a technical-debt report generated overnight and read the next morning. Your manager proposes moving both to the Message Batches API for the 50% saving. How do you answer?",
  "Move the technical-debt report to the Batches API and keep the pre-merge check synchronous.",
  ["Move both, and fall back to a synchronous call whenever a batch is taking longer than the pipeline can wait.",
   "Move both, and poll for batch status so the pipeline knows exactly when each set of results is ready.",
   "Keep both synchronous, because batch results come back in an order the pipeline cannot rely on."],
  "The Batches API carries no latency guarantee and can take up to 24 hours, which an overnight report absorbs and a developer waiting on a merge does not. A mid-run fallback pays for the same work twice, polling does not shorten the wait, and result ordering is not what rules batching out.",
  pool="practical"),
