# -*- coding: utf-8 -*-
from common import Q

D = 3  # D4 — Prompt Engineering & Structured Output

# ---------------------------------------------------------------- standard ---

Q("d4s01", D, "standard", "Claude Code for CI",
  "Your review prompt says \"check that comments are accurate and up to date\". Findings flag harmless TODO markers and plain descriptions, while missing comments that describe behaviour the code no longer has. What addresses the root cause?",
  "Replace the vague instruction with explicit criteria: flag a comment only where its claim contradicts what the code does.",
  ["Add few-shot examples of misleading comments so the model recognises the same shape elsewhere.",
   "Strip TODO, FIXME and purely descriptive comments before analysis to cut the noise at source.",
   "Supply git blame data so the model can spot comments that predate the code around them."],
  "\"Accurate and up to date\" is not a definition, so the model supplies its own and it drifts. A precise criterion fixes both failure directions at once; examples and pre-filtering work around a specification you have not written."),

Q("d4s02", D, "standard", "Claude Code for CI",
  "Findings are real but not actionable — \"complex ticket routing logic\", \"potential null pointer\", with nothing to change. Adding \"always include a concrete fix suggestion\" produced output that is sometimes detailed and sometimes still vague. Which technique reliably fixes the format?",
  "Add three or four few-shot examples showing exactly the required shape: issue, location, concrete fix.",
  ["Refine the instruction further, specifying each required part of the finding format separately.",
   "Split it into two passes, one that identifies issues and one that generates fixes for them.",
   "Widen the context to include more of the surrounding codebase so concrete fixes are possible."],
  "When instructions alone give variable output, examples are the reliable next step: they show the shape instead of describing it. More instruction text is more of what already failed, and neither splitting the work nor adding context makes the format consistent."),

Q("d4s03", D, "standard", "Conversational AI architecture",
  "An assistant has to keep an enthusiastic tone, explain its reasoning and ask clarifying questions. Where do those behavioural guidelines belong?",
  "In the system prompt.",
  ["Prepended to every user message, so they stay close to whatever the user just asked.",
   "In the first assistant message, so the model has already demonstrated the behaviour once.",
   "In environment variables read by the application before each request is assembled."],
  "The system prompt is the place for persistent behavioural constraints across a conversation. Repeating them on every user turn is redundant overhead, the model will happily drift from its own earlier message, and environment variables never reach the model at all."),

Q("d4s04", D, "standard", "Conversational AI architecture",
  "Users complain that replies keep opening with \"Certainly!\" and \"I'd be happy to help!\". What removes the pattern most reliably?",
  "Prefill the start of the assistant turn with the opening of a direct answer.",
  ["Add a system prompt instruction listing the phrases to avoid at the start of a response.",
   "Lower the temperature so the model stops reaching for its most probable opening.",
   "Strip greetings from the response in post-processing before it reaches the user."],
  "Prefilling decides the first tokens rather than asking for them, so the pattern cannot appear. Instructions catch the phrases you listed and not their variants, temperature governs randomness rather than a specific habit, and post-processing is a fragile patch."),

Q("d4s05", D, "standard", "Structured data extraction",
  "You need reliably parseable JSON out of an extraction step, matching a fixed schema. What is the standard mechanism?",
  "Define a tool whose input schema is the target JSON Schema and let the model populate it through tool_use.",
  ["Describe the JSON in the system prompt and instruct the model to reply with nothing else.",
   "Ask for JSON and repair whatever comes back with a tolerant parser before validating it.",
   "Request Markdown with one fenced JSON block and extract the block with a regular expression."],
  "Using tool_use with a JSON Schema constrains the shape at generation time, which is why it is the documented route to structured output. Everything else asks politely and then cleans up."),

Q("d4s06", D, "standard", "Structured data extraction",
  "A contract-extraction prompt handles standard agreements well, but on amendments and addenda it puts the wrong dates in the wrong fields. What is the most effective addition?",
  "Few-shot examples covering the document structures it gets wrong, not more examples of the ones it handles.",
  ["More examples of standard agreements, so the correct field mapping is reinforced overall.",
   "A longer description of each field in the schema, spelling out which date belongs where.",
   "A separate extraction pass per document type, each with its own prompt and schema."],
  "Examples earn their tokens where the model is actually uncertain. Reinforcing the cases it already handles changes nothing, and field descriptions restate a mapping it is misapplying to an unfamiliar structure."),

Q("d4s07", D, "standard", "Structured data extraction",
  "Processing 5,000 archived documents overnight through an extraction prompt, with results needed by morning. Which API approach fits, and why?",
  "The Message Batches API — it halves the cost, and its window is far inside the time available.",
  ["Synchronous calls in parallel — batch results are returned unordered, which breaks per-document mapping.",
   "Synchronous calls in sequence — batch processing does not accept JSON schemas for structured extraction.",
   "The Message Batches API with a synchronous fallback — batches often exceed their window and need rescuing."],
  "Nobody is waiting, so a 24-hour window costs nothing and saves half the spend. Ordering is handled by custom_id, schemas work normally in a batch, and building a fallback for a deadline you are nowhere near is wasted work."),

Q("d4s08", D, "standard", "Code generation with Claude Code",
  "You asked for a function transforming API responses into an internal format. Two iterations later the nesting is still wrong and timestamps are formatted differently each time. The requirements were written as prose. What works best next?",
  "Give two or three concrete input–output examples showing the exact transformation you expect.",
  ["Rewrite the requirements more precisely, specifying field mappings, nesting rules and format strings.",
   "Write a JSON Schema for the output and validate each iteration against it.",
   "Ask Claude to explain its current understanding so you can find where the interpretations diverge."],
  "Prose about structure is exactly what is being reinterpreted; an input–output pair leaves nothing to interpret. A schema catches a wrong result after the fact, and more precise prose is more of what already failed twice."),

Q("d4s09", D, "standard", "Structured data extraction",
  "A long source document is pasted into the user turn and the model starts drifting from the extraction instructions. What is the standard correction?",
  "Wrap the document in XML tags and restate the task after it as well as in the system turn.",
  ["Move the document into the system prompt so the instructions and the data live together.",
   "Cut the document down until the model stops drifting, then process the remainder separately.",
   "Reduce max_tokens so the model has less room to wander away from the instructions."],
  "Delimiting separates data from instruction, and restating the task after a long input puts it back in a reliably attended position. Instructions belong in the system turn and data in the user turn, not the other way round."),

Q("d4s10", D, "standard", "Customer support agent",
  "You want to add few-shot examples to improve tool selection on ambiguous requests like \"I need help with my recent purchase\". Which set of examples helps most?",
  "Four to six examples drawn from the ambiguous cases, each stating why one tool was chosen over the plausible alternative.",
  ["Ten to fifteen examples of clear, unambiguous requests showing correct selection for each tool.",
   "Examples grouped by tool — every get_customer case first, then every lookup_order case.",
   "\"Use when\" and \"do not use when\" notes added to each tool description rather than examples."],
  "Examples should target where the model is uncertain, and the comparison — why this tool and not that one — is what teaches the boundary. Unambiguous cases demonstrate a decision it already makes correctly."),

Q("d4s11", D, "standard", "Claude Code for CI",
  "You need an automated reviewer to distinguish acceptable patterns from genuine problems in code it has never seen. Which prompting approach is most effective?",
  "Examples of both: code that looks suspicious but is acceptable, next to code that is genuinely problematic.",
  ["Examples of problematic code only, so the model learns the shape of a real finding.",
   "A rule list describing the problematic patterns in prose, kept current as new ones appear.",
   "A severity scale, so the model can rate everything and you filter the low scores out."],
  "A boundary needs both sides. Showing only violations teaches the model what a problem looks like but not where acceptable practice ends, which is where the false positives come from."),

Q("d4s12", D, "standard", "Structured data extraction",
  "Where should the extraction instructions live relative to the document being extracted from?",
  "Instructions in the system turn, the document in the user turn, delimited so the two cannot be confused.",
  ["Both in the user turn, with the instructions immediately after the document so they are read last.",
   "Both in the system turn, so the model treats the document with the same authority as the task.",
   "Instructions in the system turn and the document prefilled into the assistant turn as context."],
  "Instructions are configuration and belong in the system turn; the document is data and belongs in the user turn. Delimiting keeps content inside the document from being read as an instruction."),

# ------------------------------------------------------------- challenging ---

Q("d4c01", D, "challenging", "Conversational AI architecture",
  "An AI tutor has a 2,800-token system prompt of teaching methodology and adaptation rules. After around twelve turns it stops adapting to proficiency level. The conversation is well within limits. What is the most effective fix?",
  "Replace the verbose declarative rules with few-shot examples demonstrating adaptation at each proficiency level.",
  ["Inject a reminder of the rules every four or five turns to re-establish them as the history grows.",
   "Move the critical rules to the end of the system prompt, where they are attended to more reliably.",
   "Evaluate each response and regenerate it whenever the difficulty level does not match the learner."],
  "Abstract rules have to be re-reasoned on every turn, which is what degrades as history accumulates; demonstrated behaviour is matched rather than derived. Reminders treat the symptom, repositioning helps early and not at turn twelve, and regeneration is expensive correction after the fact."),

Q("d4c02", D, "challenging", "Conversational AI architecture",
  "During QA, Claude follows the system prompt for the first ten to fifteen turns and then deviates. The conversation is still well inside the token limit. What is the best solution?",
  "Insert user-role messages that restate the guidelines at natural breakpoints in the conversation.",
  ["Move the behavioural guidelines into the first user message so they sit inside the conversation itself.",
   "Start a fresh conversation every twenty turns to keep the system prompt proportionally dominant.",
   "Validate each response after generation and regenerate the ones that break the guidelines."],
  "Periodic reinforcement counteracts drift as accumulated history dilutes the system prompt's influence. Moving guidelines into the first user message reduces their authority, restarting destroys context, and post-hoc validation corrects rather than prevents, at the cost of a second call."),

Q("d4c03", D, "challenging", "Conversational AI architecture",
  "An assistant with a contractor-persona system prompt follows it early on, but by turn seven gives generic advice. The whole conversation is only 2,500 tokens. What is the most likely cause?",
  "Accumulated assistant turns increasingly dominate the visible pattern, so the model matches its own recent output rather than the persona.",
  ["Attention weakens as the number of turns grows, independently of how many tokens they contain.",
   "The system prompt is sent only on the first request, so later turns run without it.",
   "System prompts set initial behaviour only, and sustained behaviour needs reinforcement in the user turns."],
  "At 2,500 tokens nothing is being lost to length. What changes is the proportion: several assistant turns of generic prose become the strongest pattern in view. The system prompt is sent every request, so its absence cannot be the explanation."),

Q("d4c04", D, "challenging", "Structured data extraction",
  "Your extraction tool is defined and the schema is right, but the model sometimes answers in prose instead of calling the tool. Which change makes the structured path deterministic?",
  "Set tool_choice so the extraction tool must be used, instead of leaving the decision to the model.",
  ["Remove every other tool from the request so extraction is the only option available to the model.",
   "Add an instruction to the system prompt requiring the extraction tool to be called on every document.",
   "Prefill the assistant turn with the opening of a tool_use block so the model has to continue it."],
  "tool_choice is the parameter that forces a tool call rather than suggesting one. Leaving a single tool available still permits a text answer, an instruction is probabilistic, and prefilling does not apply to structured tool blocks."),

Q("d4c05", D, "challenging", "Structured data extraction",
  "An extraction pipeline has a validation-and-retry loop. On a repeat failure for the same document, what should the second retry contain?",
  "Nothing further — cap the repairs and route the document to human review with both failed attempts attached.",
  ["The same repair request again, since the model often succeeds on a third attempt with identical input.",
   "A simplified schema with the failing field removed, so at least the rest of the record is captured.",
   "The document alone with no schema, so the model extracts freely and you map the fields afterwards."],
  "Bounded repair is the pattern: one informed retry, then a human. Unbounded retries burn budget on a document the model cannot handle, and quietly dropping or unstructuring the field ships an incomplete record as if it were complete."),

Q("d4c06", D, "challenging", "Claude Code for CI",
  "Severity ratings are inconsistent — a null-pointer risk is \"critical\" in one PR and \"medium\" in another, on comparable code. The prompt asks the model to \"assign an appropriate severity\". What is the most effective change?",
  "Define each severity level by observable criteria and give a worked example of each.",
  ["Have every finding rated twice in separate calls and take the higher of the two ratings.",
   "Drop severity entirely and report findings as a flat list for developers to prioritise.",
   "Ask the model to justify each rating in prose, so inconsistency becomes visible in review."],
  "\"Appropriate\" leaves the scale undefined, so it is re-invented per call. Criteria plus a worked example per level make the ratings reproducible; double-rating measures the inconsistency without removing it, and dropping severity discards useful signal."),

Q("d4c07", D, "challenging", "Customer support agent",
  "Single-issue requests are handled with 94% accuracy. When a customer raises two issues in one message — a refund on one order and an address change on another — accuracy falls to 58%, with one issue dropped or parameters mixed between them. What improves reliability most?",
  "Few-shot examples demonstrating the reasoning and tool sequencing for multi-issue requests, with parameters kept separate.",
  ["A preprocessing model call that splits multi-issue messages into separate requests, handled independently and merged after.",
   "Response validation that detects an incomplete answer and automatically reprompts to cover the missed issue.",
   "Fewer, broader tools, so there are fewer parameters to confuse between the two issues."],
  "The agent already performs well per issue; what it lacks is the pattern for handling two at once. Examples supply that directly, where a preprocessing stage adds a call and a component for something the model can do, and validation only catches the failure afterwards."),

Q("d4c08", D, "challenging", "Structured data extraction",
  "Informal quantities appear across your documents — \"a couple of boxes\", \"half a pallet\", \"approx. 3 tonnes\". The schema wants a number and a unit. Extraction currently guesses or leaves the field blank inconsistently. What is the best approach?",
  "Add examples covering the informal forms, and extend the schema with a field recording that the value was approximate.",
  ["Add an instruction to convert informal quantities into their most likely numeric equivalent.",
   "Mark the quantity field nullable and drop anything not expressed as an explicit number.",
   "Extract the raw phrase into a string field and parse it into a number in downstream code."],
  "Examples teach the conversion and the extra field keeps the fact that it was a conversion, so downstream code can treat it differently. Instructing a guess loses that provenance, dropping the values loses data, and parsing prose downstream moves the ambiguity rather than resolving it."),

Q("d4c09", D, "challenging", "Claude Code for CI",
  "You are designing a review prompt for large pull requests. Which structure produces the most consistent findings?",
  "Sequential focused passes, each with its own narrow criteria, feeding a final integration pass.",
  ["One comprehensive prompt listing every review criterion, so nothing is missed in a single reading.",
   "One prompt run three times at a higher temperature, with the findings merged afterwards.",
   "One prompt per severity level, run in parallel across the full diff each time."],
  "Chaining focused passes is what keeps depth consistent when a single pass would dilute attention across too many concerns. A single comprehensive prompt is the shape that produces the inconsistency, and repeated whole-diff runs multiply cost without narrowing what each pass attends to."),

Q("d4c10", D, "challenging", "Conversational AI architecture",
  "Requests like \"Book a venue for the party\" trigger four or more clarifying questions, and 35% of users abandon the conversation. What best improves the trade-off?",
  "State the assumptions being made explicitly, proceed on them, and invite corrections.",
  ["Ask all the clarifying questions at once in a single compound message instead of one at a time.",
   "Proceed on sensible defaults without mentioning them, and adjust if the user objects to the result.",
   "Replace the questions with a short structured intake form covering the required details."],
  "Stating assumptions gives an immediate useful answer while leaving the user in control. A compound question still demands the same effort up front, silent defaults leave the user unable to spot a wrong one, and a form adds friction in a flow that is already losing people to friction."),

Q("d4c11", D, "challenging", "Conversational AI architecture",
  "Over several turns a user has said \"I have a very low risk tolerance\" and later \"I want to maximise my returns\". They now ask what to invest in. What should the assistant do?",
  "Point out that the two stated priorities conflict and ask which one should govern the recommendation.",
  ["Act on the most recently stated preference, since it reflects the user's current thinking.",
   "Give two recommendations, one for each stated priority, and let the user pick between them.",
   "Recommend a balanced portfolio that partly satisfies both without raising the conflict."],
  "The two goals are genuinely incompatible, so any answer encodes a decision the user has not made. Surfacing the conflict is the only route that does not guess; recency is not intent, and a balanced answer buries the choice inside a recommendation."),

Q("d4c12", D, "challenging", "Conversational AI architecture",
  "Vague requests like \"Can you help with the report?\" produce several clarifying questions — which report, what kind of help, by when — and 40% of users abandon. What is the best solution?",
  "Make reasonable assumptions, state them in the reply and offer to adjust.",
  ["Use predefined interpretations for common request shapes without spelling them out to the user.",
   "Classify the ambiguity with a smaller, cheaper model first and only ask when it is genuinely unresolvable.",
   "Allow at most one clarifying question per turn, so the exchange never feels like an interrogation."],
  "Stated assumptions remove the back-and-forth while keeping the user informed and able to correct. Silent interpretations leave them confused when the answer misses, one question per turn still spends turns, and a classifier adds infrastructure without changing the experience."),
