# -*- coding: utf-8 -*-
from common import Q

D = 4  # D5 — Context Management & Reliability

# ---------------------------------------------------------------- standard ---

Q("d5s01", D, "standard", "Conversational AI architecture",
  "Users report that latency and cost both climb once a conversation passes about 50 turns. What is the primary cause?",
  "Every request carries the whole conversation history, so each call is larger than the last.",
  ["The model builds an internal profile of the user, and maintaining it costs more as it grows.",
   "Responses get progressively longer as the model has more material to refer back to.",
   "Database reads of the stored history slow down as the number of rows per conversation grows."],
  "The API is stateless, so the growing history is resent in full on every call and is billed and processed every time. There is no server-side profile, and response length is not tied to conversation length."),

Q("d5s02", D, "standard", "Multi-agent research system",
  "Aggregated subagent output runs to about 75K tokens. The synthesis agent reliably cites the first 15K and the last 10K, but keeps missing findings in the middle 50K even when they answer the research question directly. What does this describe?",
  "The lost-in-the-middle effect — long inputs are processed most reliably at their start and end.",
  ["Context window overflow — the middle section is silently truncated before the model sees it.",
   "Progressive summarisation loss — the middle was compressed when the context was compacted.",
   "Tool result accumulation — the middle is tool output the model treats as lower priority than text."],
  "Nothing is missing from the input; it is being attended to unevenly. That positional pattern is the lost-in-the-middle effect, and it is why long inputs need structure rather than just more room."),

Q("d5s03", D, "standard", "Multi-agent research system",
  "Given that positional pattern, how should the aggregated input be restructured?",
  "Put a key-findings summary at the start and organise the rest under explicit section headings.",
  ["Summarise everything down to under 20K tokens so the whole input sits in the reliable range.",
   "Alternate which subagent's results appear first from run to run, so each gets the top position over time.",
   "Stream the results in incrementally, completing the web-search set before the document analysis set."],
  "A summary at the front uses the position that is read most reliably, and headings give the model a way to navigate the middle. Compressing to 20K throws away detail, rotation shares the problem out rather than solving it, and incremental streaming just reproduces the ordering in time."),

Q("d5s04", D, "standard", "Conversational AI architecture",
  "A 40-minute cooking session has reached 78,000 tokens, covering allergies, recipe scaling, clarified terminology and general chat. You must cut tokens without losing what matters. What is the best approach?",
  "Extract the critical facts into a structured block, summarise the general discussion, and keep recent turns verbatim.",
  ["Summarise the entire conversation history into a single compact narrative.",
   "Keep the most recent 20,000 tokens verbatim and discard everything before them.",
   "Store the full conversation externally and retrieve relevant parts by semantic search."],
  "The hybrid keeps precision where it is critical, compression where it is not, and verbatim recency for coherence. Whole-conversation summarisation and a rolling window both risk losing an allergy, and external retrieval is heavy machinery for one session."),

Q("d5s05", D, "standard", "Conversational AI architecture",
  "An assistant keeps only the last 25 message pairs, and users report it losing earlier topics and preferences. What is the most effective solution?",
  "Summarise the older messages and keep the recent ones verbatim.",
  ["Raise the window to 50 message pairs so more history survives before anything is dropped.",
   "Run a vector similarity search over the full history and inject the closest matches each turn.",
   "Summarise the dropped messages every turn and prepend the running summary to the request."],
  "Recent turns need exact text for coherence, and older ones only need their substance retained. Enlarging the window postpones the same loss, similarity search misses context that is relevant without being similar, and re-summarising every turn accumulates its own errors."),

Q("d5s06", D, "standard", "Customer support agent",
  "The agent has called get_customer and lookup_order and has every fact the system holds. Which situation most clearly justifies calling escalate_to_human?",
  "A customer asks for competitor price matching; policy covers price drops on your own site but is silent on competitors.",
  ["A customer says a parcel never arrived, but tracking shows it delivered and signed for three days ago.",
   "A customer wants to cancel an order that shipped yesterday and is due to arrive tomorrow.",
   "A customer's message contains both a billing question and a return, and needs coordinating."],
  "Escalation is for a genuine policy gap, where answering would mean inventing policy. The others are awkward but decidable: the agent can present tracking evidence, apply the cancellation rules and handle two issues in one conversation."),

Q("d5s07", D, "standard", "Structured data extraction",
  "An extraction pipeline reports 97% overall accuracy, and the team proposes removing human review entirely. What is the most important objection?",
  "An aggregate can hide a document type or field that performs far worse than the average.",
  ["97% is below the 99% threshold at which automated extraction is normally considered safe.",
   "Accuracy measured on a validation set does not transfer to production without recalibration.",
   "Without human review there is no labelled data left, so accuracy can never be measured again."],
  "Aggregate metrics mask segments. Before automating you validate accuracy by document type and by field, because a single poorly-performing combination can be responsible for most of the real-world damage."),

Q("d5s08", D, "standard", "Structured data extraction",
  "You want to know how often the pipeline's high-confidence extractions are actually wrong. Which method gives you that?",
  "Stratified random sampling within the high-confidence band, reviewed against ground truth.",
  ["Reviewing every extraction the model marked low-confidence and extrapolating the error rate upward.",
   "Comparing the model's confidence scores against its own second-pass re-extraction of the same documents.",
   "Tracking how many high-confidence extractions are later corrected by downstream users."],
  "You can only measure the error rate inside a band by sampling that band and checking it against truth. Low-confidence items say nothing about high-confidence ones, self-comparison inherits the same bias, and downstream corrections only catch what somebody happened to notice."),

Q("d5s09", D, "standard", "Multi-agent research system",
  "Two credible sources disagree on a key metric: a government report says 40% growth, an industry analysis says 12%. How should the document analysis agent handle it?",
  "Finish the analysis carrying both figures, annotate the conflict with its attribution, and let the coordinator reconcile it.",
  ["Apply credibility heuristics to choose the more likely figure and footnote the discrepancy.",
   "Stop and escalate to the coordinator immediately to decide which source is authoritative before continuing.",
   "Include both figures without marking them as conflicting and let synthesis decide from wider context."],
  "The analysis agent's job is to report faithfully, not to adjudicate; reconciliation belongs to the coordinator, which has the broader view. Picking a value quietly loses the disagreement, stopping blocks work that could continue, and unmarked figures let the conflict slip through unnoticed."),

Q("d5s10", D, "standard", "Developer productivity tools",
  "During a long codebase investigation, the agent's answers become vaguer and it starts describing \"typical patterns\" instead of the actual classes it read earlier. What is happening and what helps?",
  "Context degradation over a long session; write key findings to a scratchpad file and refer back to them.",
  ["The model has switched to its training priors because the repository is unusual; provide more examples from it.",
   "Tool results have been silently dropped from the history; re-run the tool calls to restore them.",
   "The session has hit a turn limit and is running in a reduced mode; start a new session to reset it."],
  "Generic answers late in a long session are the classic sign of context degradation. A scratchpad carries specific findings across context boundaries so they survive whatever happens to the conversation history."),

# ------------------------------------------------------------- challenging ---

Q("d5c01", D, "challenging", "Customer support agent",
  "Customers refer to figures they mentioned earlier — \"the 15% discount I was offered\" — and the agent replies with the wrong number. Those details were stated more than twenty turns ago and have since been condensed into \"promotional pricing was discussed\". What fixes this?",
  "Extract transactional facts — amounts, dates, order numbers — into a case-facts block sent with every prompt, outside the summarised history.",
  ["Rewrite the summarisation prompt to preserve all numbers, percentages, dates and stated expectations verbatim.",
   "Raise the summarisation threshold from 70% to 85% so conversations run longer before anything is compressed.",
   "Store the full history externally and retrieve from it whenever the customer says \"as I mentioned\"."],
  "Summarisation loses precision by design, so the values have to live somewhere summarisation does not reach. A better summarisation prompt degrades more slowly, a higher threshold delays the same loss, and retrieval triggered by a phrase misses every reference that is worded differently."),

Q("d5c02", D, "challenging", "Multi-agent research system",
  "Combined output from the web-search agent (85K tokens of page content) and the document analysis agent (70K tokens including reasoning traces) reaches 155K tokens, but synthesis performs best under 50K. Which solution is most effective?",
  "Change the upstream agents to return structured findings — key facts, quotes, relevance — instead of raw content and reasoning.",
  ["Insert an intermediate summarisation agent that condenses the findings before they reach synthesis.",
   "Have synthesis process the findings in sequential batches, carrying state between the calls.",
   "Store the findings in a vector database and give synthesis search tools to query during its work."],
  "Fix it at the source: most of those 155K tokens are page content and reasoning traces that synthesis never needed. Every other option pays to transport, compress or index material that should not have been produced in that form."),

Q("d5c03", D, "challenging", "Multi-agent research system",
  "The web-search subagent covers only three of five requested source categories — competitor sites and industry reports succeed, news archives and social feeds time out. Document analysis processed everything it was given. Synthesis must now produce a summary from uneven inputs. Which propagation strategy is best?",
  "Have synthesis annotate its coverage, marking which conclusions are well supported and where gaps remain because sources were unavailable.",
  ["Have synthesis return an error to the coordinator so the task is retried or failed on incomplete data.",
   "Have synthesis ask the coordinator to retry the timed-out sources with a longer timeout before it begins.",
   "Proceed with the successful sources and produce a clean summary without noting what was unavailable."],
  "Graceful degradation with transparency preserves the value of completed work while carrying the uncertainty forward, so whoever reads the report knows what it rests on. Failing the task discards good work, blocking on a retry stalls it, and silence misrepresents partial coverage as complete."),

Q("d5c04", D, "challenging", "Multi-agent research system",
  "A subagent queries three source categories: academic databases return 15 papers, industry reports return \"0 results\", patent databases return \"Connection timeout\". Which error-propagation design supports the best recovery decisions?",
  "Report the access failure and the empty result as distinct outcomes, since only one of them warrants a retry.",
  ["Report both the timeout and the zero results as failures needing a coordinator decision.",
   "Retry transient failures inside the subagent and report only errors that persist after retries.",
   "Aggregate the three outcomes into a coverage percentage, with detailed logs available on request."],
  "\"No patents exist\" is a finding; \"we could not reach the patent database\" is an outage. Collapsing them either sends the coordinator chasing a result that is already complete or hides a failure inside a percentage."),

Q("d5c05", D, "challenging", "Conversational AI architecture",
  "After three months of weekly sessions the history is around 85,000 tokens. A user asks \"what did we conclude about the theme of isolation?\" and gets a generic answer instead of a reference to the earlier discussion. What is the most effective approach?",
  "Index the exchanges as embeddings and retrieve the relevant ones on demand.",
  ["Progressive summarisation that captures the key conclusions from each session as it ends.",
   "A rolling window that keeps the most recent sessions in full and discards the older ones.",
   "Structured tags marking conclusions in the history so they can be located when needed."],
  "At three months of accumulated discussion, retrieval is the only approach that can still surface a specific exchange on demand. Summarisation abstracts away the particular conclusion being asked for, a rolling window has already discarded it, and tagging requires restructuring everything that came before."),

Q("d5c06", D, "challenging", "Structured data extraction",
  "Field-level confidence scores are available. How should the human review threshold be set?",
  "Calibrate it against a labelled validation set, so the chosen score corresponds to a measured error rate.",
  ["Set it where the review queue matches the capacity of the team available to work it.",
   "Set it at a round number such as 0.9 and adjust it as corrections come back from downstream users.",
   "Set it per document type at the mean confidence the model reports for that type."],
  "A confidence score is only meaningful once you know what it predicts, which is what a labelled set establishes. Sizing the queue to the team picks a threshold from staffing rather than risk, a round number is arbitrary, and a mean sends half of every type to review by construction."),

Q("d5c07", D, "challenging", "Multi-agent research system",
  "Your final reports read well but nobody can tell which source supports which claim. Subagents currently return polished prose summaries. What is the minimum change that restores attribution?",
  "Require subagents to emit claim-to-source mappings — the quote, the document or URL, and the date — and preserve them through aggregation.",
  ["Have the report-writing agent add a bibliography of every document the subagents consulted.",
   "Have the coordinator attach each subagent's full output as an appendix to the report.",
   "Have synthesis re-check each claim against the sources and cite the ones it can confirm."],
  "Attribution is lost during summarisation unless the mapping is produced with the claim and carried through aggregation. A bibliography says what was read, an appendix makes the reader do the work, and re-checking pays for the same research twice."),

Q("d5c08", D, "challenging", "Multi-agent research system",
  "Two sources report different figures for the same metric, and it turns out one was collected in 2023 and the other in 2025. Your reports have been presenting this as a contradiction. What should change?",
  "Require collection or publication dates alongside every figure, so a change over time is not read as a disagreement.",
  ["Prefer the most recent source whenever two figures conflict, and drop the older value from the report.",
   "Treat conflicting figures as unreliable and exclude both unless a third source agrees with one of them.",
   "Report the range between the two figures, which covers both values without adjudicating between them."],
  "Without dates, a trend is indistinguishable from a contradiction. Dropping the older value discards the trend, excluding both discards the finding, and a range presents movement over time as measurement uncertainty."),

Q("d5c09", D, "challenging", "Developer productivity tools",
  "An agent investigating a large codebase spends most of its context on verbose discovery output before it reaches the question you actually asked. Which combination handles this best?",
  "Delegate discovery to subagents, write the findings to a scratchpad, and summarise before starting the next phase.",
  ["Raise the context window and run /compact whenever usage approaches the new limit.",
   "Split the investigation across several sessions, each resuming the previous one with --resume.",
   "Reduce what each tool returns and instruct the agent to re-read files whenever it needs them again."],
  "Discovery is verbose by nature, so it belongs somewhere other than the main context, with a durable record of what it found. Compaction still pays for the output first, resuming carries stale results forward, and re-reading trades context for repeated tool calls."),

Q("d5c10", D, "challenging", "Customer support agent",
  "Your team wants to add crash recovery so a long-running agent task can resume after a process restart. What has to be persisted for that to work?",
  "Structured state — the task, what has been completed, and the findings so far — rather than the raw conversation.",
  ["The full messages array exactly as sent, so the conversation can be replayed from the beginning.",
   "The session identifier, so the provider can restore the conversation from its own stored copy.",
   "The last assistant response, from which the agent can infer where it had reached and continue."],
  "Recovery needs a record of progress, not a transcript to replay: replaying re-executes side effects and re-pays for tokens. There is no provider-side copy to restore, and one response does not describe what has already been done."),
