# -*- coding: utf-8 -*-
"""The source's classification items, rewritten as multiple-response items.

The real paper is 63 standalone multiple-choice and multiple-response items, so
each "classify these five statements" exercise becomes a four-option item that
asks for the two statements belonging to one category. The statements and the
reasoning are the source's; the stem and the option set are the rewrite."""

# key: (source array, index) -> replacement item. 'a' is the correct pair.
CONVERSIONS = {
 ("REVIEW", 40): dict(
   q="Which TWO of these RAG activities are post-processing rather than pre-processing?",
   o=["Chunking documents at section boundaries with overlap",
      "Re-ranking retrieved passages before assembling the prompt",
      "Redacting personal data from source documents before embedding",
      "Dropping retrieved chunks below a relevance threshold"],
   a=[1, 3],
   e="Anything done to sources before indexing is pre-processing — chunking, redaction, metadata extraction. Anything applied to retrieved hits or to the generated answer is post-processing: re-ranking and threshold filtering both act on what retrieval returned."),
 ("REVIEW", 41): dict(
   q="Which TWO descriptions are structure-aware chunking?",
   o=["Split every document into 512-token pieces regardless of content",
      "Cut contracts at clause headings and manuals at section titles",
      "Detect topic shifts with embeddings and cut where meaning changes",
      "Split a code base by function and class definitions"],
   a=[1, 3],
   e="Structure-aware chunking uses the document's own boundaries — clauses, headings, functions. Fixed-size ignores structure entirely, and semantic chunking cuts on meaning shifts it detects rather than on markup the document already carries."),
 ("REVIEW", 42): dict(
   q="Which TWO statements about evaluation are FALSE?",
   o=["The prompt-tuning examples can double as the reported evaluation set if there are enough of them",
      "An LLM judge should be calibrated against human labels before its scores are trusted",
      "A change that raises quality but doubles latency can ship without checking the SLA",
      "Production failures should become new evaluation cases"],
   a=[0, 2],
   e="Held-out data, judge calibration, multi-axis gates and closing the loop are the core practices. A set you tuned against cannot report your score, and a quality gain that breaks the latency SLA is a regression on the axis the stakeholder named."),
 ("REVIEW", 43): dict(
   q="Which TWO of these controls are preventive — they remove or block the action itself?",
   o=["Removing a write tool the role never needs",
      "Human approval before an external email is sent",
      "A hook that blocks any shell command containing rm -rf",
      "Audit logging of every tool call"],
   a=[0, 2],
   e="Removal and programmatic blocks prevent: the action cannot happen. An approval gate is compensating — the capability exists and a human decides. Logging is detective: it tells you afterwards."),
 ("REVIEW", 44): dict(
   q="Which TWO activities belong to the discovery phase?",
   o=["Agreeing measurable success criteria with the sponsor",
      "Choosing between a workflow and an agent and recording the decision",
      "Interviewing compliance about data-residency constraints",
      "Delivering runbooks and rollback steps to operations"],
   a=[0, 2],
   e="Discovery defines the problem, the measurable target and the constraints. Deciding and recording the architecture is design; runbooks and rollback are handoff."),

 ("MOCK_STD", 9): dict(
   q="Which TWO of these descriptions are workflows rather than an agent or an augmented LLM?",
   o=["A classifier dispatches each request to one of four specialised prompts along code-defined paths",
      "The model decides which of its tools to call next based on the previous result until it judges the task complete",
      "Steps are orchestrated by code with validation gates between model calls",
      "A single model call enriched with retrieved policy text and a currency-conversion tool, returning one answer"],
   a=[0, 2],
   e="Workflows follow predefined code paths — routing and chaining with gates are both workflows. An agent decides its own steps dynamically; an augmented LLM is one enriched call with no loop at all."),
 ("MOCK_STD", 10): dict(
   q="Which TWO targets are performance-SLA commitments rather than efficiency or cost commitments?",
   o=["Keep p95 response latency under 2 seconds during peak hours",
      "Reduce average handle time per support ticket from 14 to 9 minutes",
      "Guarantee 99.9% monthly availability of the assistant endpoint",
      "Bring spend per resolved case below $0.05 including model and review"],
   a=[0, 2],
   e="Performance SLAs are service guarantees: latency percentiles, availability, an accuracy floor. Handle time is efficiency — the same work in less human time — and spend per resolved case is cost."),
 ("MOCK_STD", 18): dict(
   q="Which TWO statements about prompt caching are FALSE?",
   o=["Any content block can be cached regardless of its position in the request",
      "Cache reads are billed at a lower rate than standard input tokens and reduce time-to-first-token",
      "Prompt caching is available only when requests are submitted through the Message Batches API",
      "A change to content before a cache breakpoint invalidates the cached prefix from that point onward"],
   a=[0, 2],
   e="Caching is prefix-based, so position decides what can be cached and an edit upstream of a breakpoint invalidates everything after it. Reads are cheaper and faster than standard input, writes cost more, and it is a synchronous-API feature as well as a batch one."),
 ("MOCK_STD", 29): dict(
   q="Which TWO of these RAG pipeline activities are post-processing rather than pre-processing?",
   o=["Re-ranking the retrieved passages with a cross-encoder before assembling the context",
      "Redacting personal data from documents before they are embedded",
      "Attaching citations to the generated answer from the passages actually used",
      "Deduplicating near-identical documents so the index does not contain multiple copies"],
   a=[0, 2],
   e="Ingestion-side work — cleaning, redaction, metadata, deduplication, chunking, embedding — is pre-processing. Anything applied to retrieved hits or to generated output, such as re-ranking, filtering, citation or validation, is post-processing."),
 ("MOCK_STD", 30): dict(
   q="Which TWO descriptions match parent-child chunking?",
   o=["Retrieve on small sentence-level chunks but pass the enclosing section to the model for generation",
      "Split every document into 400-token windows that share 50 tokens with the previous window",
      "Index paragraphs for matching while returning the full parent page as context",
      "Split contracts at clause boundaries and manuals at headings so each chunk is one semantic unit"],
   a=[0, 2],
   e="Parent-child separates the unit used for matching from the unit passed to the model, which is how you get precise retrieval without losing surrounding context. Fixed windows with overlap ignore structure; structure-aware chunking follows the document's own boundaries."),
 ("MOCK_STD", 40): dict(
   q="Which TWO symptoms point to a grounding or hallucination problem rather than to a prompt failure or a model mismatch?",
   o=["Invented product SKUs appearing mainly when the catalogue search returned no results",
      "Correct facts but inconsistent field names and occasional prose around the JSON",
      "Confident regulatory citations that do not exist, concentrated on out-of-corpus topics",
      "Accurate on single-currency invoices, wrong on multi-currency invoices with nested discounts"],
   a=[0, 2],
   e="Fabricated specifics that cluster where retrieval found nothing are a grounding failure. Format and instruction adherence is a prompt failure; errors that track task complexity are a model mismatch."),
 ("MOCK_STD", 49): dict(
   q="Which TWO statements about the risks of LLM systems are FALSE?",
   o=["A larger model tier eliminates prompt-injection risk because it follows the system prompt more faithfully",
      "A model version change behind a floating alias can silently alter output format and refusal behaviour",
      "Setting temperature to 0 guarantees byte-identical outputs for identical inputs",
      "Instructions hidden in retrieved documents can be followed by the model if the content is not treated as untrusted data"],
   a=[0, 2],
   e="Model size does not remove injection, and temperature 0 lowers variance without guaranteeing determinism — note that both false options contain an absolute. Version drift behind an alias and injection through retrieved content are both real failure modes."),
 ("MOCK_STD", 58): dict(
   q="Which TWO of these problems should have been prevented at handoff and monitoring?",
   o=["On-call cannot tell which prompt version was live when an incident occurred",
      "Success was described as “reduce workload” with no measurable target",
      "Quality regressions are only discovered when customers complain",
      "The team is unsure whether the mid-tier model meets the quality floor for complex cases"],
   a=[0, 2],
   e="Version telemetry and quality signals are handoff and monitoring concerns. A target nobody made measurable is a discovery failure, and an unknown model fit is settled in design and evaluation."),
 ("MOCK_STD", 62): dict(
   q="Which TWO incidents belong to the data and retrieval layer rather than to integration or model output?",
   o=["Answers cite last quarter's prices after the catalogue was updated yesterday",
      "HTTP 429 responses during the 09:00 traffic peak",
      "Confident answers about a product line that was removed from the knowledge base",
      "Correct data returned but the output schema does not match what the parser expects"],
   a=[0, 2],
   e="Stale or withdrawn content reaching the answer is an indexing and refresh problem. Rate limits are integration-layer and transient; a schema that does not match the parser is model output."),

 ("MOCK_CHL", 10): dict(
   q="Which TWO scenarios justify an agent rather than a workflow or a single augmented call?",
   o=["Investigate an outage where each diagnostic step depends on what the previous step revealed",
      "Nightly: classify 80,000 tickets, route billing tickets to a lookup step, draft replies, queue for approval",
      "Negotiate with a supplier over several rounds, deciding which concessions to explore based on their replies",
      "Extract twelve fixed fields from an invoice, validate them in code, write to the ERP"],
   a=[0, 2],
   e="Agency is justified when the number and order of steps depend on what the model discovers. The nightly pipeline and the extraction path are both enumerable before the request arrives, which makes them workflows."),
 ("MOCK_CHL", 18): dict(
   q="Which TWO statements describe Agent Skills rather than an MCP server or prompt caching?",
   o=["Packages a reusable procedure that Claude loads only when the task matches its description",
      "Exposes authenticated access to a live ticketing system to any compliant client application",
      "Is the right home for “how we write incident reports here”",
      "Requires the static content to come before the dynamic content in the request"],
   a=[0, 2],
   e="Skills carry procedural knowledge, loaded on demand instead of bloating every system prompt. MCP carries capabilities and authenticated access; caching reuses a stable prefix, which is why order matters for it."),
 ("MOCK_CHL", 30): dict(
   q="Which TWO of these RAG activities are post-processing rather than pre-processing?",
   o=["Filtering retrieved chunks by tenant and recency metadata before assembly",
      "Converting PDFs to text and stripping headers, footers and boilerplate",
      "Checking that every claim in the generated answer is supported by a retrieved passage",
      "Computing and storing embeddings with the embedding model version recorded"],
   a=[0, 2],
   e="Ingestion-side work — conversion, cleaning, chunking, embedding — is pre-processing. Metadata filtering of retrieved hits and groundedness checking of the answer both act after retrieval."),
 ("MOCK_CHL", 40): dict(
   q="Which TWO statements about evaluation practice are FALSE?",
   o=["An evaluation set used to tune the prompt can also be used to report the final score if it is large enough",
      "A cost optimisation that drops accuracy below the agreed floor is a regression, not a saving",
      "Model swaps do not require re-evaluation as long as the prompt is unchanged",
      "Production failures should be converted into new evaluation cases"],
   a=[0, 2],
   e="Held-out data, re-evaluation on any change — model included — and closing the loop from production are the core practices. Size does not make a tuned set held out, and a new model changes format, verbosity and refusal behaviour whatever the prompt does."),
 ("MOCK_CHL", 49): dict(
   q="Which TWO controls are preventive — they remove or block the action itself?",
   o=["Removing the account-deletion tool from an agent whose users never delete accounts",
      "Requiring a human approval before any transfer above a threshold",
      "A PreToolUse hook that refuses any shell command containing a destructive flag",
      "Logging every tool call with inputs and outputs for later audit"],
   a=[0, 2],
   e="Removal and programmatic blocks sit at the top of the control hierarchy: the capability is gone or the call never executes. An approval gate is compensating, and logging is detective."),
 ("MOCK_CHL", 58): dict(
   q="Which TWO activities belong to the design phase?",
   o=["Writing the decision record that captures why a workflow was chosen over an agent",
      "Interviewing frontline staff and compliance to define success criteria and constraints",
      "Defining the evaluation plan and control stack for the chosen architecture",
      "Delivering runbooks and rollback procedures to the operations team"],
   a=[0, 2],
   e="Design chooses the architecture and documents it, and settles the evaluation plan and controls before build. Interviews that produce success criteria are discovery; runbooks and rollback are handoff."),
 ("MOCK_CHL", 62): dict(
   q="Which TWO incidents are transient integration-layer problems?",
   o=["HTTP 429 during the 09:00 peak with retries disabled",
      "Correct data but the output schema does not match the parser's expectation",
      "A 529 overloaded response during a provider incident",
      "Answers cite last month's prices after yesterday's catalogue update"],
   a=[0, 2],
   e="Rate limits and provider overload are transient integration failures, handled with backoff and retry policy. A schema mismatch is model output; stale prices are a data and retrieval problem."),
}
