# -*- coding: utf-8 -*-
"""Authored CCAR-P metadata: domain framing and one lead sentence per sub-skill.

The bullet points and traps come from the source study guide; the framing below
is written from the same guide's prose (decision rules and exam traps)."""

DOMAIN_META = {
 1: dict(short="Solution design",
   summary="Qualifying the problem, the four-stage architecture spine, the pattern ladder, multi-agent trade-offs and decomposition.",
   intro="Getting from an ambiguous business problem to the least complicated architecture that satisfies it — and being able to say why you stopped there. Almost every wrong answer in this domain is more sophisticated than the right one."),
 2: dict(short="Models & context",
   summary="Model tiers, system prompts and guardrails, prompting techniques, context budgets, caching and Skills.",
   intro="Only 13% of the paper, and the domain candidates over-prepare because it is the most familiar. Learn the proportionality rule, the context-budget techniques and the reuse mechanisms by name, then spend the time you would have spent on prompt wording on domains 5 and 6."),
 3: dict(short="Integration",
   summary="Tool surface, identity and authorisation, latency trades, observability, RAG, protocols and progressive disclosure.",
   intro="The largest single domain — bigger than solution design. The exam's view is that architecture on paper is the easy half, and the marks are in tool interfaces, authorisation, retrieval design and observability, which is where production systems actually fail."),
 4: dict(short="Evaluation",
   summary="Metrics on five axes, datasets and graders, A/B and rollout, diagnosis, cost and latency optimisation, monitoring.",
   intro="Measurement and the discipline that comes with it: nothing is optimised before it is measured, nothing ships without a regression gate, and every production failure becomes a test case. “Measure before you change” resolves a surprising share of these items on its own."),
 5: dict(short="Governance",
   summary="Layered guardrails, failure modes, human gates, GDPR / HIPAA / FedRAMP, and ethics as a design input.",
   intro="Where enforcement beats instruction. When a scenario asks for a guarantee, the answer is a mechanism — a removed capability, a blocking hook, an approval gate — and never a sentence in the system prompt."),
 6: dict(short="Stakeholders & lifecycle",
   summary="Discovery, decision records, SLAs and expectations, handoff documentation, and the five lifecycle phases.",
   intro="The domain engineers skip and then lose marks on. It is learnable rather than experiential: discovery before design, trade-offs recorded rather than argued, measured performance rather than promises, and a handoff a team you will never meet can operate."),
 7: dict(short="Dev productivity",
   summary="Team configuration for Claude Code, AI-assisted developer workflows, and operational debugging.",
   intro="The smallest domain at 7% — roughly four questions — and the cheapest marks on the paper if you have configured Claude Code for a team and been on call for something it touched."),
}

# One lead sentence per sub-skill, in blueprint order.
LEADS = {
 (1,0): "The first question is not how Claude would do this, but whether a language model should do it at all. Discovery settles that, and it settles it before any architecture is drawn.",
 (1,1): "Every end-to-end design the exam asks about has the same four stages — input, processing, output, feedback — and candidates reliably design three of them.",
 (1,2): "A complexity ladder: a single augmented call, prompt chaining, routing, parallelisation, orchestrator–workers, evaluator–optimiser, autonomous agent. Start at the bottom and climb only when an evaluation shows the lower rung misses the bar.",
 (1,3): "Multi-agent designs earn their cost in two situations — parallel breadth and context isolation — and hurt in most of the others.",
 (1,4): "Four axes to cut a complex problem along, and one rule governing all of them: decompose until each unit is independently testable, then stop.",
 (1,5): "Classify the stated goal into a pillar, because the pillar decides the metric you commit to. Cost per successfully completed task is the figure that matters, not cost per API call.",
 (2,0): "Proportionality: match the tier to the difficulty and the stakes. “Use Opus to be safe” is a wrong answer on a high-volume classifier, and so is a floating alias in production.",
 (2,1): "The system prompt carries the invariants and the user turn carries the data — and neither of them enforces anything. Money, deletions and regulated outputs need programmatic controls.",
 (2,2): "Zero-shot, few-shot and chain-of-thought are a difficulty ladder rather than a stack. Every rung costs tokens and latency, so climb only when the task needs it.",
 (2,3): "Context is a finite budget with diminishing returns. The goal is the smallest set of high-signal tokens, not the largest window you can afford.",
 (2,4): "Three mechanisms for not repeating yourself — prompt caching, modular prompts and Skills — solving three different problems. Scenarios name them, so know the shape and the limits of each.",
 (3,0): "Too many tools is an architecture problem, not a prompting problem: it degrades tool selection, inflates every request and widens the attack surface.",
 (3,1): "Authentication is who is calling; authorisation is what they may do. The agent must act with the end user's effective permissions, never a service account's superset.",
 (3,2): "Every step you add buys accuracy with latency and cost. The exam wants that trade made explicitly, in numbers, against the SLA the scenario stated.",
 (3,3): "In a multi-step system the symptom surfaces several steps after its cause, so the unit of observability is the trace, not the request.",
 (3,4): "Chunking and indexing are where retrieval quality is decided. Everything downstream is either benefiting from those decisions or compensating for them.",
 (3,5): "The shape of the data and the shape of the query decide the strategy. Embedding everything and hoping is the default the exam punishes.",
 (3,6): "MCP, a direct API or CLI call, or agent-to-agent: the choice turns on reuse and ownership boundaries, not on capability.",
 (3,7): "Front-loading every tool and document into every request is simple and, at enterprise scale, expensive. Progressive disclosure is the preference, with a small always-on core.",
 (4,0): "Five axes — accuracy, latency, cost, safety, security — and one rule: optimise the axis the stakeholder named and hold the rest as constraints.",
 (4,1): "A dataset that looks like real traffic plus the edge cases that break it, graded by the cheapest method that can grade it, and versioned like code.",
 (4,2): "Version, regression-test, evaluate offline, shadow, canary, roll out — one variable at a time, with a changelog linking each change to its measured delta.",
 (4,3): "Attribute before you fix. Prompt failure, hallucination and model mismatch have different signatures, and a wrong attribution costs an engineering cycle.",
 (4,4): "The levers in rough order of impact, and the floor that governs all of them: an optimisation that drops below the agreed quality floor is a regression, not a saving.",
 (4,5): "Telemetry that lets you reconstruct a run months later, quality signals that catch drift the error rate never sees, and a path by which failures become evaluation cases.",
 (5,0): "Controls form a hierarchy of strength, and the stack you build scales with the blast radius rather than with how worried the room is.",
 (5,1): "The failure modes are known and enumerable. The professional skill is mapping each one to a control, an owner and a graceful degradation.",
 (5,2): "Put humans where the blast radius is, and make the gate architectural: the action does not execute until the approval exists.",
 (5,3): "GDPR, HIPAA and FedRAMP ask different questions, but the controls that answer them recur — redact before the model, isolate tenants, log, retain, delete on request.",
 (5,4): "Bias, transparency and accountability are design inputs with architectural consequences: segmented evaluations, citations, disclosure and named owners.",
 (6,0): "Discovery converts “add AI to support” into a problem, a measurable target and a constraint list — and it finishes before design starts.",
 (6,1): "A decision is communicated as a trade-off against the pillar the stakeholder named, and recorded where it will outlive the team that made it.",
 (6,2): "Never promise 100%. Commit to measured performance on an agreed evaluation set, and separate the SLAs engineering controls from the quality SLOs it measures.",
 (6,3): "The handoff package is part of the architecture: an undocumented system cannot be operated to an SLA.",
 (6,4): "Five phases, each with exit criteria and artefacts. A recurring item type hands you a symptom and asks which phase should have caught it.",
 (7,0): "Team standards belong in version-controlled project configuration; organisation policy belongs in managed settings that take precedence over both.",
 (7,1): "Gains become organisational when they are packaged and shared — skills, commands, prompts — and measured in cycle time rather than in enthusiasm.",
 (7,2): "Leave on-call equipped: reproducible traces, runbooks, and an incident taxonomy that routes each failure to the layer that owns it.",
}
